hmcts/probate-frontend

- app/resources/en/translation/copies/overseas.json
- app/resources/en/translation/copies/uk.json
- app/steps/ui/copies/overseas/schema.json
- app/steps/ui/copies/uk/schema.json
- test/component/copies/testCopiesOverseas.js
- test/component/copies/testCopiesUk.js
Fields for the number of UK copies and overseas copies are now a required field
> Pro 2058 extra uk overseascopiesexplicit

- package.json
- test/config.js
- test/smoke/healthcheck.js
- yarn.lock
PRO-2481: CNP: create test:smoke for frontend
Added frontend smoke tests
```
[ ] Yes
[x] No
```
> PRO-2481: Frontend smoke tests

- app.js
- app/components/utils.js
- app/config.js
- app/healthcheck.js
- Set up in one of two ways based on CNP-Enabled variable
```
[ ] Yes
[ ] No
```
> PRO-2423: Add Redis initialization for CNP

- app/components/logger.js
- package.json
- yarn.lock
PRO-2421: Implement logging for CNP - Frontend
PRO-2421: Implement logging for CNP - Frontend
- Replaced bunyan with nodejs-logging
```
[ ] Yes
[x] No
```
> PRO-2421: Implement logging for CNP - Frontend

- app/core/initSteps.js
PRO-2509: CNP: Fix probate fronted path issue in windows 
Use path module to determine the file path separator instead of hardcoding it so we can deploy the app to both Linux and Windows
```
[ ] Yes
[x] No
```
> PRO-2509 - CNP: Fix probate fronted path issue in windows 

- app/utils/FormatName.js
- test/unit/testFormatName.js
Add default values for firstName and lastName in case only one is given and trim leading and trailing spaces
```
[ ] Yes
[x] No
```
> Improve FormatName util

- pre-commit.sh
Improve pre-commit script
- Only check test files for .only references
- Fix rejected file list so each file is displayed on a new line
```
[ ] Yes
[x] No
```
> Improve pre-commit script

- app/routes.js
- app/steps/ui/executors/address/index.js
- app/steps/ui/executors/currentname/index.js
- app/steps/ui/executors/othername/index.js
- app/wrappers/Executors.js
- test/unit/testExecutorsWrapper.js
Refactoring including using ExecutorWrapper methods and using arrow functions in the routes
```
[ ] Yes
[x] No
```
> Refactoring to use ExecutorWrapper methods

- pre-commit.sh
Add ESLint check to the pre-commit hook
```
[ ] Yes
[x] No
```
> Add ESLint check to the pre-commit hook

- app/steps/ui/summary/includes/deceased.njk
https://tools.hmcts.net/jira/browse/PRO-1123
Original change failed testing as one instance remained.  Now fixed.
```
[ ] Yes
[x] No
```
> PRO-1123: Remove hidden text on change/answer links

- .eslintignore
- app/assets/javascripts/gatracking.js
- app/views/includes/scripts.html
https://tools.hmcts.net/jira/browse/PRO-2635
Moving GA Tracking to an external file
```
[ ] Yes
[ x] No
```
> Pro 2635 google analytics not captured

- app.js
- app/config.js
- package.json
https://tools.hmcts.net/jira/browse/PRO-2624
**Add App Insights tracking**
This adds basic analytics, and provides a base for adding additional custom analytics if it's required. There is an environment variable `APPINSIGHTS_INSTRUMENTATION_KEY` to set the access key in the Ansible scripts.
```
[ ] Yes
[x] No
```
> PRO-2624: Add app insights tracking

- package.json
Update https-proxy-agent version to 2.2.1
```
[ ] Yes
[x] No
```
> Update https-proxy-agent version to 2.2.1

- app/resources/en/translation/applicant/phone.json
- app/steps/ui/applicant/phone/template.html
https://tools.hmcts.net/jira/browse/PRO-2727
Removed paragraph text from template
Removed value from phone.json file
```
[ ] Yes
[x ] No
```
> Pro 2727 phone number page content changes

- app/config.js
Update payload version for release
https://tools.hmcts.net/jira/browse/PRO-2765
> PRO-2765: Update payload version

- app/assets/sass/application-common.scss
- app/assets/sass/application-ie8.scss
- app/assets/sass/application.scss
Move placement of public/images/ directory reference 
```
[ ] Yes
[x] No
```
> Fix missing images.

- app/routes.js
> set content-type header in test APIs

- Jenkinsfile
> pull ansible management for install/deploy playbooks to work.

- .travis.yml
- app/resources/en/translation/deceased/alias.json
- app/routes.js
- app/steps/ui/deceased/alias/index.js
- app/steps/ui/deceased/alias/template.html
- infrastructure/saat.tfvars
- test/component/deceased/testAlias.js
https://tools.hmcts.net/jira/browse/PRO-2750
Added Deceased's name using session variable and updated the test for that page.
```
[ ] Yes
[x] No
```
> PRO-2750 - Added deceased's name and updated test

- infrastructure/saat.tfvars
Change frontend to not use IDAM
```
[ ] Yes
[x] No
```
> PRO-Change frontend to not use IDAM

- app/utils/FormatUrl.js
Add logging for api urls
```
[ ] Yes
[x] No
```
> Add logging for api urls

- infrastructure/saat.tfvars
Fix persistance service url
```
[ ] Yes
[x] No
```
> Fix persistance service url

- app/components/services.js
Add logging for the loadFormData url
```
[ ] Yes
[x] No
```
> Add logging for the loadFormData url

- bin/run-functional-tests.sh
- package.json
> PRO-2541 : Integration of e2e

- app/core/runners/UIStepRunner.js
Pro add handle get logging
```
[ ] Yes
[x] No
```
> Add handleGet logging

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
**Update config**
- Syntax errors
- probate_frontend_use_idam = true"
```
[ ] Yes
[x] No
```
> Pro config update

- test/end-to-end/codecept.conf.js
- test/end-to-end/helpers/PuppeteerHelper.js
- test/end-to-end/pages/payment/govukpayment.js
- test/end-to-end/paths/multipleExecutorsPath.js
- test/end-to-end/paths/singleExecutorsPath.js
> E2e updates

- test/end-to-end/codecept.conf.js
Increase timeout for CNP
```
[ ] Yes
[x ] No
```
> Increase timeout for CNP

- test/config.js
- test/end-to-end/helpers/TestConfigurator.js
- test/end-to-end/paths/multipleExecutorsPath.js
- test/end-to-end/paths/singleExecutorsPath.js
> Cnp e2e updates

- app/config.js
- app/healthcheck.js
- app/utils/Healthcheck.js
- test/service-stubs/business.js
- test/service-stubs/persistence.js
- test/service-stubs/submit.js
- test/unit/testHealthcheckUtil.js
https://tools.hmcts.net/jira/browse/PRO-2840
Add git commit id of the downstream services in the frontend `/health` endpoint
- Refactored methods from `/health` route into new utils class and added unit tests
- Added `/health` and `/info` endpoints to the business, persistence and submit stubs
```
[ ] Yes
[x] No
```
> PRO-2840 - CNP: Add show /info in frontend health end point of backend

- app/components/services.js
- infrastructure/saat.tfvars
https://tools.hmcts.net/jira/browse/PRO-3102
Update S2S body params format and change payment_return_url to use https
```
[ ] Yes
[x] No
```
> PRO-3102 - CNP: Update S2S body params format

- infrastructure/demo.tfvars
- infrastructure/saat.tfvars
> corrected Demo URL

- infrastructure/aat.tfvars
> change idam flag in aat

- app/config.js
N/A
Fix environment property name for app insights
```
[ ] Yes
[x ] No
```
> Fix environment property name

- app/resources/en/translation/deceased/alias.json
- app/steps/ui/summary/includes/deceased.njk
- app/steps/ui/summary/index.js
- test/component/deceased/testAlias.js
- test/component/summary/testDeceasedSection.js
> Pro 3130 deceased name summary page

- app/resources/en/translation/applicant/nameasonwill.json
- app/resources/en/translation/deceased/alias.json
- app/steps/ui/summary/includes/deceased.njk
- app/steps/ui/summary/includes/executors.njk
- app/steps/ui/summary/index.js
- infrastructure/preview.tfvars
- test/component/applicant/testNameAsOnWill.js
- test/component/deceased/testAlias.js
- test/component/summary/testDeceasedSection.js
- test/component/summary/testExecutorsSection.js
https://tools.hmcts.net/jira/browse/PRO-3130
https://tools.hmcts.net/jira/browse/PRO-3131
https://tools.hmcts.net/jira/browse/PRO-3176
Check Your Answers fixes
```
[ ] Yes
[x ] No
```
> Release to master: PRO-3130, PRO-3131, PRO-3176

- app/resources/en/translation/deceased/alias.json
- app/steps/ui/summary/includes/deceased.njk
- app/steps/ui/summary/index.js
- test/component/deceased/testAlias.js
- test/component/summary/testDeceasedSection.js
https://tools.hmcts.net/jira/browse/PRO-3130
**1. Replace deceasedName token with the name of the deceased**
- If the user has entered the name of the deceased then replace the deceasedName token with the name
- If the user has not yet entered the name of the deceased then replaced the token with default text
- Move the logic of the married name out of the template
**2. Add component tests for the new deceased name content**
```
[ ] Yes
[x] No
```
> PRO-3130 - Check your answer page is displaying deceased variable rather than the actual value of the variable

- app.js
- app/config.js
https://tools.hmcts.net/jira/browse/PRO-2448
Set cookie flags: secure and http to true
```
[ ] Yes
[x ] No
```
> PRO-2448: Set req.session.cookie.secure based on the req.protocol value

- app.js
- app/config.js
- app/routes.js
https://tools.hmcts.net/jira/browse/PRO-2449
Do not allowing caching on the client (browser)
```
[ ] Yes
[ x] No
```
> Pro 2449 prevent https response caching

- test/config.js
- test/end-to-end/helpers/TestConfigurator.js
- test/end-to-end/paths/multipleExecutorsPath.js
- test/end-to-end/paths/singleExecutorsPath.js
https://tools.hmcts.net/jira/browse/PRO-3206
Retry scenarios in the pipeline if they fail
```
[ ] Yes
[x ] No
```
> CNP Pipeline

- app/assets/javascripts/gatracking.js
- app/views/includes/scripts.html
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/PRO-2635
Change description
Put GA code inline
```
[ ] Yes
[x ] No
```
> PRO-2635: Google analytics not capturing data

- app/config.js
Add sign-out page to whitelisted pages so that users are not redirected to tasklist once they reach a certain part of the journey
```
[ ] Yes
[ ] No
```
> Pro 1699 fix save and close

- test/component/deceased/testAlias.js
https://tools.hmcts.net/jira/browse/PRO-1941
Fix component test
```
[ ] Yes
[ ] No
```
> PRO-1941 - Multiple applicants – Limit number of applying executors to four

- app/resources/en/translation/deceased/otherNames.json
- app/steps/ui/deceased/otherNames/template.html
- app/views/widgets/addresslookup.html
- test/component/deceased/testOtherNames.js
https://tools.hmcts.net/jira/browse/PRO-2754
Accessibility fix
```
[ ] Yes
[x ] No
```
> Pro 2754 accessibility find address and add other name set focus to button

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- bin/run-functional-tests.sh
>  Added switch for e2e

- app/steps/ui/signout/template.html
> PRO-2839: Fixed A11y test on SignOut

- app/resources/en/translation/common.json
- app/views/includes/phase_banner_alpha.html
- app/views/includes/phase_banner_beta.html
https://tools.hmcts.net/jira/browse/PRO-2752
GDS Accessibility fix
```
[ ] Yes
[x ] No
```
> Pro 2752 accessibility open feedback link in new window

- app/steps/ui/startpage/template.html
https://tools.hmcts.net/jira/browse/PRO-2839
Fix missing List Items - GDS
```
[ ] Yes
[ x] No
```
> Pro 2590 missing list item

- app/assets/sass/application-common.scss
- app/assets/sass/application-ie8.scss
- app/assets/sass/application.scss
- app/assets/sass/patterns/_task-list.scss
- app/resources/en/translation/tasklist.json
- app/steps/ui/tasklist/includes/copies.html
- app/steps/ui/tasklist/includes/documents.html
- app/steps/ui/tasklist/includes/eligibility.html
- app/steps/ui/tasklist/includes/executors.html
- app/steps/ui/tasklist/includes/payment.html
- app/steps/ui/tasklist/includes/reviewAndConfirm.html
- app/steps/ui/tasklist/template.html
- app/views/widgets/lists.html
- app/views/widgets/taskheader.html
- app/views/widgets/taskstatus.html
- test/component/testTasklistPage.js
https://tools.hmcts.net/jira/browse/PRO-3026
Tasklist changes to make GDS compliant
```
[ ] Yes
[ x] No
```
> Pro 3026 task list design change

- app/steps/ui/startpage/template.html
> PRO-2590 Add missing list item

- app/assets/sass/application-common.scss
- app/assets/sass/application-ie8.scss
- app/assets/sass/application.scss
- app/assets/sass/patterns/_task-list.scss
- app/resources/en/translation/tasklist.json
- app/steps/ui/tasklist/includes/copies.html
- app/steps/ui/tasklist/includes/documents.html
- app/steps/ui/tasklist/includes/eligibility.html
- app/steps/ui/tasklist/includes/executors.html
- app/steps/ui/tasklist/includes/payment.html
- app/steps/ui/tasklist/includes/reviewAndConfirm.html
- app/steps/ui/tasklist/template.html
- app/views/widgets/lists.html
- app/views/widgets/taskheader.html
- app/views/widgets/taskstatus.html
- test/component/testTasklistPage.js
https://tools.hmcts.net/jira/browse/PRO-3026
Task list "completed lozenge" to align with GDS style. Moved 'Can't start' text into a new file. 
No tests added.
```
[ ] Yes
[x] No
```
> PRO-3026: Design Changes to Task list

- app/journeys/probate.js
- app/resources/en/translation/executors/mentalcapacity.json
- app/resources/en/translation/stoppage.json
- app/steps/ui/executors/mentalcapacity/index.js
- app/steps/ui/executors/mentalcapacity/schema.json
- app/steps/ui/executors/mentalcapacity/template.html
- app/steps/ui/summary/includes/will.njk
- test/component/applicant/testExecutor.js
- test/component/executors/testMentalCapacity.js
- test/component/summary/testWillSection.js
- test/component/testStopPage.js
- test/data/complete-form.json
- test/data/multipleApplicant.json
- test/data/singleApplicant.json
- test/data/will.json
- test/end-to-end/pages/executors/mentalcapacity.js
- test/end-to-end/pages/steps.js
- test/end-to-end/paths/multipleExecutorsPath.js
- test/end-to-end/paths/singleExecutorsPath.js
- test/unit/testMentalCapacity.js
- test/unit/testTasklist.js
> PRO-3032 - Mental incapacity screening question - Merged with demo

- app/journeys/probate.js
- app/resources/en/translation/executors/mentalcapacity.json
- app/resources/en/translation/stoppage.json
- app/steps/ui/executors/mentalcapacity/index.js
- app/steps/ui/executors/mentalcapacity/schema.json
- app/steps/ui/executors/mentalcapacity/template.html
- app/steps/ui/summary/includes/will.njk
- test/component/applicant/testExecutor.js
- test/component/executors/testMentalCapacity.js
- test/component/summary/testWillSection.js
- test/component/testStopPage.js
- test/data/complete-form.json
- test/data/multipleApplicant.json
- test/data/singleApplicant.json
- test/data/will.json
- test/end-to-end/pages/executors/mentalcapacity.js
- test/end-to-end/pages/steps.js
- test/end-to-end/paths/multipleExecutorsPath.js
- test/end-to-end/paths/singleExecutorsPath.js
- test/unit/testMentalCapacity.js
- test/unit/testTasklist.js
https://tools.hmcts.net/jira/browse/PRO-3032
Mental Incapacity Question added to journey
```
[ ] Yes
[x ] No
```
> PRO-2032: Add Mental Incapacity question to user journey

- app/config.js
- app/journeys/probate.js
- app/resources/en/translation/deceased/deathcertificate.json
- app/resources/en/translation/stoppage.json
- app/steps/ui/deceased/deathcertificate/index.js
- app/steps/ui/deceased/deathcertificate/schema.json
- app/steps/ui/deceased/deathcertificate/template.html
- app/steps/ui/stoppage/template.html
- app/steps/ui/summary/includes/will.njk
- test/component/testStopPage.js
- test/component/will/testWillCodicils.js
- test/component/will/testWillCodicilsNumber.js
- test/data/complete-form.json
- test/unit/testTasklist.js
> Pro 1700 f merge conflicts

- test/end-to-end/pages/deceased/deathcertificate.js
- test/end-to-end/pages/steps.js
- test/end-to-end/paths/multipleExecutorsPath.js
- test/end-to-end/paths/singleExecutorsPath.js
https://tools.hmcts.net/jira/browse/PRO-1700
Add e2e tests
```
[ ] Yes
[x] No
```
> PRO-1700 - Add e2e tests

- app/steps/ui/payment/breakdown/index.js
- test/data/complete-form-undeclared.json
- test/service-stubs/payment.js
- test/unit/testPaymentBreakdown.js
- test/unit/testPaymentStatus.js
https://tools.hmcts.net/jira/browse/PRO-3066
Handle payment failures  gracefully
```
[ ] Yes
[x ] No
```
> Pro 3165 handle s2 s failures before create payment

- package.json
Change the order the coverage tests are run in because this is breaking a unit test
```
[ ] Yes
[ ] No
```
> PRO-3165: Fix failing unit test in the code coverage

- test/end-to-end/pages/IDAM/signIn.js
https://tools.hmcts.net/jira/browse/PRO-3066
Fix e2e test
```
[ ] Yes
[ x] No
```
> Fix e2e tests

- app/config.js
- app/utils/FormatUrl.js
https://tools.hmcts.net/jira/browse/PRO-3333
```
[ ] Yes
[ x] No
```
> PRO-3333: fix Access Denied because of http

- app/components/security.js
- app/config.js
- app/utils/FormatUrl.js
- package.json
- test/unit/testFormatUrl.js
https://tools.hmcts.net/jira/browse/PRO-3332
https://tools.hmcts.net/jira/browse/PRO-3333
```
[ ] Yes
[x] No
```
> fix not authorised & Access Denied problem

- app/resources/en/translation/executors/names.json
- infrastructure/preview.tfvars
https://tools.hmcts.net/jira/browse/PRO-2470
Changing capitalisation of the executor text link.
```
[ ] Yes
[x] No
```
> PRO-2470: Change capitalisation.

- app/components/logger.js
- app/core/runners/RedirectRunner.js
- app/core/runners/UIStepRunner.js
https://tools.hmcts.net/jira/browse/PRO-3363
- Ensure email is saved into the form data before application is submitted
- Also add additional logging
```
[ ] Yes
[x] No
```
> PRO-3363 - Fix prod missing email making user unable to submit application

- app/utils/Healthcheck.js
- test/unit/testHealthcheckUtil.js
**Rename validation service dependency in the healthcheck**
- Validation Service > Business Service
```
[ ] Yes
[x] No
```
> [PREVIEW] PRO-2840: Rename validation service dependency in the healthcheck

- app/resources/en/translation/executors/invite.json
- app/steps/ui/executors/invite/index.js
- app/steps/ui/executors/invite/template.html
- test/component/executors/testExecutorsInvite.js
- test/data/executors-invites.json
- test/unit/testExecutorsInvite.js
- if more than one other executor then the placement of the apostrophe is different
- component tests updated to test for correct content
```
[ ] Yes
[ ] No
```
> [PREVIEW] PRO-2456: Implement conditional rendering of content on invites page

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/preview.tfvars
- infrastructure/prod.tfvars
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
> changed tactical payment to CNP payment

- infrastructure/preview.tfvars
> [PREVIEW] PRO-DOUG-TEST

- infrastructure/prod.tfvars
https://tools.hmcts.net/jira/browse/PRO-3660
```
[ ] Yes
[x] No
```
> PRO-3660 : DNS Change - SIDAM

- app/assets/sass/application-common.scss
- app/assets/sass/patterns/_check-your-answers.scss
- app/steps/ui/copies/summary/template.html
- app/steps/ui/summary/includes/deceased.njk
- app/steps/ui/summary/includes/executors.njk
- app/steps/ui/summary/includes/will.njk
- app/steps/ui/summary/template.html
- app/views/widgets/checkanswer.html
- yarn.lock
https://tools.hmcts.net/jira/browse/PRO-3175
Implement the new GDS Design System patterns for Check Your Answers/Summary page.  This is also 
used on the copies summary page.  It now uses a definition list <dl>,<dt> and <dd> instead of tables.
```
[ ] Yes
[x] No
```
> [PREVIEW] Pro 3175 f implement new gds design system pattern for check your answers

- app/components/services.js
- app/config.js
- app/utils/FeatureToggle.js
- test/service-stubs/persistence.js
- test/unit/testFeatureToggle.js
https://tools.hmcts.net/jira/browse/PRO-3207
Add unit tests and update persistence service stub
```
[ ] Yes
[x] No
```
> [PREVIEW] PRO-3207 Unit Tests and Stub

- app/components/step-utils.js
- app/steps/ui/applicant/alias/index.js
- app/steps/ui/applicant/aliasreason/index.js
- test/component/summary/testExecutorsSection.js
- test/unit/testApplicantAlias.js
- test/unit/testApplicantAliasReason.js
https://tools.hmcts.net/jira/browse/PRO-3780 
```
[ ] Yes
[X] No
```
> [PREVIEW] PRO-3780 - About You: If "is your name" is "no" then you end up in a loop

- app/components/submit-data.js
- app/config.js
- app/resources/en/translation/iht/paper.json
- app/steps/ui/iht/paper/index.js
- app/steps/ui/iht/paper/schema.json
- app/steps/ui/iht/paper/template.html
- test/component/iht/testPaper.js
- test/component/summary/testIHTSection.js
- test/data/complete-form-multipleapplicants.json
- test/data/ihtPaper.json
- test/unit/testSoftStops.js
- test/unit/testSubmitData.js
PRO-3442 - add iht form type for submission to ccd
https://tools.hmcts.net/jira/browse/PRO-3442
In conjunction with
https://tools.hmcts.net/jira/browse/PRO-3547
https://tools.hmcts.net/jira/browse/PRO-3548
https://tools.hmcts.net/jira/browse/PRO-3615
```
[ ] Yes
[ x] No
```
> Pro 3442 add iht form type

- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/main.tf
- infrastructure/saat.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
- infrastructure/variables.tf
- package.json
- sonar-project.properties
> [PREVIEW] Azure central

- test/component/payment/testPaymentStatus.js
> fixed test

- app/components/payment-data.js
- app/components/services.js
- app/config.js
- app/steps/ui/payment/breakdown/index.js
- app/steps/ui/payment/status/index.js
- test/unit/testPaymentData.js
https://tools.hmcts.net/jira/browse/PRO-2312
**Integrate with the payment hub API**
1. Update payment config
- Update createPaymentUrl
- Update applicationFeeCode
- Update serviceId
- Update siteId
- Add version
- Add currency
2. Update payment-data to set data require for payments v2
3. Update payment URLs to those required for v2
4. Update ccdCaseId and paymentId in payment-breakdown
5. Update data returned from the payment in payment-status
6. Update payment-data unit tests
```
[ ] Yes
[x] No
```
> PRO-2312 - Integrate with the payment hub API

- app/components/security.js
- app/routes.js
> Cnp email logging

- app/components/payment-data.js
- test/unit/testPaymentData.js
https://tools.hmcts.net/jira/browse/PRO-3867
Changed `createPaymentData()` so application fee is only added if there is an application fee to pay.
Added unit tests for `createPaymentData()`
```
[ ] Yes
[x] No
```
> [PREVIEW] PRO-3867 - Don't submit payment code for application is application fee is 0

- app/assets/javascripts/document-upload.js
- app/assets/sass/application-common.scss
- app/assets/sass/patterns/_document-upload.scss
- app/resources/en/translation/common.json
- app/views/includes/document-upload.html
- app/views/includes/help_details.html
- app/views/includes/scripts.html
https://tools.hmcts.net/jira/browse/PRO-3754
Add validation for invalid file types.
```
[ ] Yes
[x] No
```
> [PREVIEW] PRO-3754 - Upload death certificate - Rejected File Types

- app/steps/ui/declaration/index.js
- app/utils/FormatName.js
- test/component/testDeclarationPageMultipleApplicants.js
- test/component/testDeclarationPageSingleApplicant.js
- test/unit/testDeclaration.js
- test/unit/testFormatName.js
- re-write tests
- implement changes where necessary on declaration page and wrapper functions
```
[ ] Yes
[ ] No
```
> [PREVIEW] PRO-3660: Fix feature toggle to work with the declaration page

- infrastructure/main.tf
> [PREVIEW] Moved to azure vault

- app/components/submit-data.js
- infrastructure/preview.tfvars
- test/data/complete-form-multipleapplicants.json
- test/unit/testSubmitData.js
- yarn.lock
As part of the registry fix from submit service, we need to ensure we send the submission reference to the update payment status endpoint on submit service.
```
[ ] Yes
[X] No
```
> [PREVIEW] PRO-3960: Send submission reference to backend on submit data payload.

- app/featureToggles.js
> [PREVIEW] PRO-3965: Add Tasklist route to Feature Toggles

- app/assets/javascripts/document-upload.js
- app/assets/sass/patterns/_document-upload.scss
https://tools.hmcts.net/jira/browse/PRO-3756
Add styling for the progress indicator
```
[ ] Yes
[x] No
```
> [PREVIEW] PRO-3756 - Upload death certificate (progress indicator; JS only)

- Dockerfile
- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- infrastructure/main.tf
- kubernetes/.lint.yml
- kubernetes/README.md
- kubernetes/config.aat.yaml
- kubernetes/deployment.template.yaml
> Added AKS code

- app.js
- app/assets/javascripts/document-upload.js
- app/assets/sass/patterns/_document-upload.scss
- app/config.js
- app/documentUpload.js
- app/resources/en/translation/common.json
- app/resources/en/translation/documentupload.json
- app/steps/ui/documentupload/index.js
- app/utils/DocumentUpload.js
- app/views/includes/scripts.html
- test/unit/testDocumentUpload.js
- test/unit/testDocumentUploadUtil.js
- yarn.lock
https://tools.hmcts.net/jira/browse/PRO-3773
Document upload - Add validation for the maximum document file size to the non-js version
```
[ ] Yes
[x] No
```
> [PREVIEW] PRO-3773 - Upload death certificate - File Size - Non JS

- app/config.js
- app/resources/en/translation/common.json
- test/config.js
> PRO-4072: update AD information

- app/config.js
- package.json
https://tools.hmcts.net/jira/browse/PRO-3983
Remove SameSite key/value from redis.cookie in app/config.js
```
[ ] Yes
[x ] No
```
> Pro 3983 ios session lost

- app/config.js
> dr test 123 test

- infrastructure/sprod.tfvars
https://tools.hmcts.net/jira/browse/PRO-3491
```
[ ] Yes
[ ] No
```
> PRO-3491: update sprod tfvars

- app/config.js
- app/featureToggles.js
- app/steps/ui/applicant/alias/index.js
- app/steps/ui/applicant/aliasreason/index.js
- app/steps/ui/declaration/index.js
- app/steps/ui/executors/currentname/index.js
- app/steps/ui/executors/currentnamereason/index.js
- app/steps/ui/summary/includes/executors.njk
- app/steps/ui/summary/index.js
- app/utils/FormatName.js
- kubernetes/config.aat.yaml
- test/component/applicant/testAlias.js
- test/component/applicant/testAliasReason.js
- test/component/executors/testExecutorCurrentName.js
- test/component/executors/testExecutorCurrentNameReason.js
- test/component/summary/testExecutorsSection.js
- test/component/testDeclarationPageMultipleApplicants.js
- test/component/testDeclarationPageSingleApplicant.js
- test/component/will/testWillCodicils.js
- test/data/complete-form-multipleapplicants.json
- test/data/summary-executors.json
- test/unit/testApplicantAlias.js
- test/unit/testApplicantAliasReason.js
- test/unit/testDeclaration.js
- test/unit/testExecutorCurrentName.js
- test/unit/testFeatureToggle.js
- test/unit/testFormatName.js
- test/unit/testSubmitData.js
- test/unit/testSummary.js
> Prave pro 3966 msh test

- app/resources/en/translation/iht/paper.json
https://tools.hmcts.net/jira/browse/PRO-3897
```
[ ] Yes
[ ] No
```
> PRO-3897: amend gross400/net400 content on iht-paper

- app/components/services.js
- commit-msg.sh
https://tools.hmcts.net/jira/browse/PRI-111
Update the commit message git hook to accept both PRO and PRI JIRA numbers
```
[ ] Yes
[x] No
```
> PRI-111 - Tech: Change commit message git hook

- app/featureToggles.js
- app/resources/en/translation/documentupload.json
- app/resources/en/translation/summary.json
- app/steps/ui/summary/includes/documentupload.njk
- app/steps/ui/summary/index.js
- app/steps/ui/summary/template.html
- kubernetes/config.aat.yaml
- test/component/summary/testDocumentUploadSection.js
- test/component/summary/testSummary.js
- test/data/documentupload.json
- test/unit/testSummary.js
> Pro 3750 upload check your answers

- app/config.js
https://tools.hmcts.net/jira/browse/PRO-4077
Add missing renunciation url on the documents page
```
[ ] Yes
[x] No
```
> PRO-4077: Add missing renunciation url

- app.js
https://tools.hmcts.net/jira/browse/PRO-1543
```
[ ] Yes
[ ] No
```
> PRO-1543: Amend app insights setup

- app.js
Reverts hmcts/probate-frontend#508
> Revert "PRO-1543: Amend app insights setup"

- Dockerfile
Resolves CNP-1103
Hello, this PR adds the following enhancements:
improve the ordering of the docker image build layer
prepare for future ACR cache optimisations.
This is part of a general pipelines optimisations initiative and should not impact the current builds.
https://tools.hmcts.net/jira/browse/CNP-1103
Add Dockerfile optimisations such as multi-staging and reduce the amount of layering. This is in preparation for ACR. 
```
[ ] Yes
[ x] No
```
> cnp-1103-Add Dockerfile optimisations

- app/steps/ui/documents/template.html
https://tools.hmcts.net/jira/browse/PRO-4534
Add html id attribute to coversheet element
[ ] Yes
[x] No
> PRO-4534: Add html id to coversheet link element

- app.js
Reverts hmcts/probate-frontend#544
> "PRO-1543: Amend app insights setup""

- app/resources/en/translation/iht/paper.json
https://tools.hmcts.net/jira/browse/PRO-4587
Copy change on the IHT paper page
```
[ ] Yes
[X] No
```
> PRO-4587: Copy Change

- app/resources/en/translation/common.json
https://tools.hmcts.net/jira/browse/PRO-4548
Change contact email address
```
[ ] Yes
[X] No
```
> PRI-4548: Change contact email address

- Jenkinsfile_CNP
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/requirements.yaml
- charts/probate-frontend/tests/test-service.yaml
- charts/probate-frontend/values.aat.template.yaml
- charts/probate-frontend/values.template.yaml
Adding chart for frontend, include Feature Toggle api from chart, and Reddis.
```
[ ] Yes
[x ] No
```
> PRO-4734 Add Chart inc Feature Toggle

- Jenkinsfile_CNP
> revert to AKS in Jenkinsfile

- app/steps/ui/applicant/address/schema.json
- app/steps/ui/deceased/address/schema.json
- app/steps/ui/executors/address/schema.json
- test/component/applicant/testAddress.js
- test/component/deceased/testAddress.js
- test/component/executors/testExecutorsAddress.js
https://tools.hmcts.net/jira/browse/PRO-4523
```
[ ] Yes
[ ] No
```
> Pro 4523 limit freetext address boxes

- Jenkinsfile_nightly
- bin/run-functional-tests.sh
- security.sh
> set up probate frontend security scan

- app/resources/en/translation/screeners/starteligibility.json
https://tools.hmcts.net/jira/browse/PRO-4629
Updated welsh forms on start eligibility page
```
[ ] Yes
[ x  ] No
```
> PRO-4629: Updated welsh forms on start eligibility

- app/resources/en/translation/applicant/name.json
- app/resources/en/translation/deceased/name.json
- app/resources/en/translation/deceased/otherNames.json
- app/steps/ui/applicant/name/template.html
- app/steps/ui/deceased/name/template.html
- app/steps/ui/deceased/otherNames/template.html
https://tools.hmcts.net/jira/browse/PRO-4730
Added new name labels to form
```
[ ] Yes
[ x ] No
```
> PRO-4730: Updated name labels

- app/resources/en/translation/assets/overseas.json
- app/steps/ui/assets/overseas/index.js
- app/steps/ui/assets/overseas/template.html
- app/steps/ui/copies/summary/index.js
- app/steps/ui/copies/summary/template.html
- test/component/assets/testAssetsOverseas.js
- test/unit/testAssetsOverseas.js
https://tools.hmcts.net/jira/browse/PRO-4894
Dynamic deceased name on Assets Overseas page
```
[ ] Yes
[X] No
```
> PRO-4894: Dynamic deceased name on Assets Overseas page

- app/steps/ui/deceased/alias/index.js
- test/unit/testDeclaration.js
https://tools.hmcts.net/jira/browse/PRO-4040
Fix post handler method in deceased alias file
```
[ ] Yes
[ x ] No
```
> PRO-4040: Deceased alias fix post handler

- app/resources/en/translation/iht/paper.json
https://tools.hmcts.net/jira/browse/PRO-4631
Amended inheritance tax paper form labels (content change)
```
[ ] Yes
[ x ] No
```
> PRO-4631: Amended inheritance paper labels

- app/config.js
https://tools.hmcts.net/jira/browse/PRO-4907
Whitelisted footer links outside IDAM
```
[ ] Yes
[ x ] No
```
> PRO-4907: Whitelisted footer links outside IDAM

- charts/probate-frontend/values.aat.template.yaml
> PRO-5005: Test SIDAM

- infrastructure/aat.tfvars
> PRO-5005: SIDAM test

- infrastructure/aat.tfvars
> PRO-5005: SIDAM Testing

- infrastructure/aat.tfvars
> PRO-5005: SIDAM updates

- app/assets/sass/patterns/_document-upload.scss
- app/resources/en/translation/documentupload.json
- app/steps/ui/documentupload/template.html
https://tools.hmcts.net/jira/browse/PRO-4970
Update document upload content
```
[ ] Yes
[x] No
```
> PRO-4970: Update Document Upload content

- Jenkinsfile_CNP
> Add SIDAM curl

- app/steps/ui/declaration/template.html
- app/steps/ui/summary/template.html
- app/steps/ui/thankyou/template.html
- app/views/includes/scripts.html
https://tools.hmcts.net/jira/browse/PRO-5112
Address some issues raised by Sonar
```
[ ] Yes
[X] No
```
> PRO-5112: Address some Sonar issues

- package.json
> PRO-5112: Exclude checkanswer.html from sonar scan

- Jenkinsfile_CNP
> stop prod deploy

- app/resources/en/translation/screeners/starteligibility.json
- app/steps/ui/screeners/starteligibility/template.html
https://tools.hmcts.net/jira/browse/PRO-5147
Add 4 paragraph to the Start Eligibility page
```
[ ] Yes
[X] No
```
> PRO-5147: Start Eligibility content change

- test/end-to-end/paths/intestacy/intestacyPath.js
- test/end-to-end/paths/intestacy/intestacyPath1.js
https://tools.hmcts.net/jira/browse/PRO-5169
skip intestacy e2e in PA Frontend until intestacy work is back in the development lifecycle
```
[ ] Yes
[X] No
```
> PRO-5169: Skip Intestacy e2e test until further notice

- Jenkinsfile_CNP
> resume prod deploy

- Jenkinsfile_CNP
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/requirements.yaml
- charts/probate-frontend/values.template.yaml
adds the sidam whitelist job to PRs
[ ] Yes
[x ] No
```
> add sidam chart job

- infrastructure/demo.tfvars
- infrastructure/hmctsdemo.tfvars
- infrastructure/sandbox.tfvars
- infrastructure/sprod.tfvars
> PRO-0000: correct fees url in sprod.tfvars

- app/steps/ui/deceased/name/template.html
https://tools.hmcts.net/jira/browse/PRO-4947
Increase number of characters for deceased forename and last name fields
```
[ ] Yes
[x] No
```
> PRO-4947: Increase maxlength of deceased name to 100

- Jenkinsfile_CNP
- [x ] commit messages are meaningful and follow good commit message guidelines
- [ x] README and other documentation has been updated / added (if needed)
- [x ] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```
> PRO-5247: Disable pact tests for FrontEnd

- .gitignore
- test/contract/pact/probate/ProbateCheckAnswersPdfClient.spec.js
- test/contract/pact/probate/ProbateCoverSheetPdfClient.spec.js
- test/contract/pact/probate/ProbateDeclarationPdfClient.spec.js
- test/data/pacts/probate/coverSheet.json
- test/data/pacts/probate/invalidNoApplicantEmailAddressCoverSheet.json
- test/data/pacts/probate/invalidNoTitlelegalDeclaration.json
> PACT-Invalid-Interactions-Added

- Jenkinsfile_CNP
> test the pipeline

- infrastructure/demo.tfvars
> commit demosidam changes to master

- app/steps/ui/screeners/willleft/index.js
- test/unit/screeners/testWillLeft.js
> Pro 5313 stop will left in formdata

- app/config.js
- app/utils/CheckAnswersSummaryJSONObjectBuilder.js
- app/utils/LegalDocumentJSONObjectBuilder.js
- app/views/widgets/addresslookup.html
- test/data/legalDeclarationPDF.json
- test/unit/testLegalDocumentJSONObjectBuilder.js
PRO-5383: add | safe to html variable
```
[ ] Yes
[x ] No
```
> PRO-5383: add | safe to html variable

- app/config.js
- app/routes.js
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/requirements.yaml
- charts/probate-frontend/values.preview.template.yaml
- test/unit/testliveness.js
> PRO-5474: Update chart versions and add liveness unit test

- app/core/steps/AddressStep.js
- app/steps/ui/executors/address/index.js
- test/unit/testAddressStep.js
- test/unit/testExecutorAddress.js
PRO-5404 Addittional validation address line 1
```
[ ] Yes
[x ] No
```
> PRO-5404 Addittional validation address line 1

- app/resources/en/translation/applicant/relationshiptodeceased.json
https://tools.hmcts.net/jira/browse/PRO-5508
Amend copy of one answer to Relationship To Deceased
```
[ ] Yes
[X] No
```
> PRO-5508: Amend copy of one answer to Relationship To Deceased

- app/config.js
- package.json
- test/service-stubs/feature-toggles.js
- test/service-stubs/persistence.js
https://tools.hmcts.net/jira/browse/PRO-5542
Create a stub for Feature Toggles
```
[ ] Yes
[X] No
```
> Feature Toggles stub

- app/resources/en/translation/thankyou.json
https://tools.hmcts.net/jira/browse/PRO-5599
Content change on the thank you page
```
[ ] Yes
[x] No
```
> PRO-5599: Add word to thank you page

- app/resources/en/translation/screeners/ihtcompleted.json
- app/steps/ui/screeners/ihtcompleted/template.html
https://tools.hmcts.net/jira/browse/PRO-5073
Iht screener content change. 
```
[ ] Yes
[x] No
```
> PRO-5073: Add hint to iht screener

- bin/run-crossbrowser-tests.sh
- test/config.js
- test/end-to-end/helpers/WebDriverHelper.js
- test/end-to-end/pages/declaration/declaration.js
- test/end-to-end/pages/documents/documents.js
- test/end-to-end/pages/documentupload/documentupload.js
- test/end-to-end/pages/summary/summary.js
- test/end-to-end/pages/thankyou/thankyou.js
- test/end-to-end/paths/cookieBanner.js
- test/end-to-end/paths/probate/multipleExecutorsPath.js
> Dr test crossbrowser

- charts/probate-frontend/values.yaml
Increase default CPU level to prevent pod restarts
[x ] No
```
> Increase CPU default  for PRs

- app/steps/ui/copies/uk/index.js
PRO-5560: test for executors before deleting addresses
```
[ ] Yes
[ ] No
```
> PRO-5560: test for executors before deleting addresses

- test/end-to-end/pages/coapplicant/agree.js
- test/end-to-end/paths/probate/multipleExecutorsPath.js
> PRO-1234: Test

- app/views/includes/scripts.html
- package.json
- yarn.lock
N/A
Upgrade webchat to 0.1.21
```
[ ] Yes
[X] No
```
> Upgrade webchat to 0.1.21

- package.json
> re add sonar scan

- README.md
> trigger to test

- .eslintrc.js
- app/components/logger.js
- app/core/initSteps.js
- app/routes.js
- app/wrappers/DetectDataChange.js
- package.json
- test/api/addressLookup.js
- test/unit/testPostcodeAddressService.js
- yarn.lock
https://tools.hmcts.net/jira/browse/PRO-5724
Upgrade Eslint to 6.0.1
```
[ ] Yes
[X] No
```
> PRO-5724: Eslint Upgrade

- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/requirements.yaml
> update feature toggle

- test/end-to-end/helpers/PuppeteerHelper.js
> O-1234: e2e

- test/end-to-end/helpers/JSWait.js
https://tools.hmcts.net/jira/browse/PRO-5740
Prevent E2E test failing regularly at GOV PAY on IE11 and Edge
```
[ ] Yes
[x] No
```
> Pro 5740 fix e2e ie11 edge

- app/assets/javascripts/document-upload.js
- app/assets/javascripts/dropzone.js
- app/middleware/documentUpload.js
- test/unit/testDocumentUploadMiddleware.js
> Pro 5537 fix document remove

- app/steps/ui/screeners/willleft/index.js
- test/unit/screeners/testWillLeft.js
PRO-5771: reset formdata on change of caseType
```
[ ] Yes
[ ] No
```
> PRO-5771: reset formdata on change of caseType

- app/steps/ui/documentupload/index.js
- app/steps/ui/summary/includes/documentupload.njk
- test/data/complete-form.json
- test/unit/testDocumentUpload.js
- test/unit/testTasklist.js
> PRO-5075: Return to doc upload page after sign out. Toggle

- test/end-to-end/paths/intestacy/childPath.js
- test/end-to-end/paths/intestacy/spousePath.js
> PRO-1234: Add retries to the scenarios for intestacy

- test/end-to-end/paths/intestacy/childPath.js
- test/end-to-end/paths/intestacy/spousePath.js
> PRO-1234: Shorten Intestacy e2e paths

- Jenkinsfile_CNP
remove old config, seeing if it helps
> Cleanup jenkinsfile

- charts/probate-frontend/requirements.yaml
> update feature toggle chart

- Dockerfile
- app/resources/en/translation/common.json
- app/steps/ui/thankyou/template.html
Add noreferrer to survey links
```
[ ] Yes
[X] No
```
> Add noreferrer to survey links

- app/services/InviteLink.js
- charts/probate-frontend/values.preview.template.yaml
- test/unit/testDocumentUploadMiddleware.js
- test/unit/testInviteLinkService.js
https://tools.hmcts.net/jira/browse/PRO-5526
Fix bug which prevents executors from being notified if names have accents. 
```
[ ] Yes
[x] No
```
> Pro 5526 fix accent bug

- test/end-to-end/helpers/SauceLabsReportingHelper.js
https://tools.hmcts.net/jira/browse/PRO-6235
Fix broken nightly saucelabs e2e
```
[ ] Yes
[X] No
```
> Fix broken nightly

- app/config.js
- app/resources/en/translation/static/accessibility.json
- app/steps/ui/static/accessibility/template.html
https://tools.hmcts.net/jira/browse/PRO-6279
Amends to the Accessibility Statement page
```
[ ] Yes
[X] No
```
> PRO-6279: Amends to the Accessibility Statement page

- README.md
- app/components/security.js
- app/config.js
- test/component/testSecurity.js
- test/config.js
- test/service-stubs/business.js
- test/unit/testHealthcheckUtil.js
- test/unit/testSecurity.js
https://tools.hmcts.net/jira/browse/PRO-6145
Change config for new local set up
```
[ ] Yes
[x] No
```
> Pro 6145 fix local set up

- app/steps/ui/executors/whodied/index.js
https://tools.hmcts.net/jira/browse/PRO-6353
IHTC - Remove main applicant from the who died list
```
[ ] Yes
[x] No
```
> Pro 6353 remove main applicant from dead

- README.md
- app/components/security.js
- app/config.js
- test/component/testSecurity.js
- test/config.js
- test/service-stubs/business.js
- test/unit/testHealthcheckUtil.js
- test/unit/testSecurity.js
Reverts hmcts/probate-frontend#998
> Revert "Pro 6145 fix local set up"

- app/steps/ui/executors/dealingwithestate/index.js
- test/component/executors/testExecutorsDealing.js
- test/unit/executors/testExecutorsDealing.js
https://tools.hmcts.net/jira/browse/PRO-6352
Dealing with estate should show current name
```
[ ] Yes
[x] No
```
> Pro 6352 show correct name dealing with estate alias

- app/steps/ui/deceased/alias/index.js
- app/steps/ui/deceased/otherNames/index.js
- test/unit/deceased/testDeceasedAlias.js
https://tools.hmcts.net/jira/browse/PRO-6358
Make sure deceased aliases are removed from ccd
```
[ ] Yes
[ x] No
```
> Pro 6358 remove deceased alias from ccd

- app/steps/ui/applicant/address/template.html
- app/steps/ui/deceased/address/template.html
- app/steps/ui/executors/address/template.html
- app/views/includes/document-upload.html
- app/views/includes/two_thirds_form.html
https://tools.hmcts.net/jira/browse/PRO-5061
Turn off autocomplete on input fields
```
[ ] Yes
[X] No
```
>  PRO-5061: Turn off autocomplete

- README.md
- app/components/security.js
- app/config.js
- charts/probate-frontend/values.preview.template.yaml
- infrastructure/main.tf
- test/component/testSecurity.js
- test/config.js
- test/service-stubs/business.js
- test/unit/testHealthcheckUtil.js
- test/unit/testSecurity.js
Reverts hmcts/probate-frontend#1001
> Revert "Revert "Pro 6145 fix local set up""

- app/core/runners/UIStepRunner.js
fix citizen draft updates after payment fialure
> PRO-6536: fix case update after pay failed

- app/services/CoverSheetPdf.js
- app/steps/ui/payment/status/index.js
- test/unit/payment/testPaymentStatus.js
> PRO-6535: Coversheet fix for registry details

- Jenkinsfile_CNP
- app/steps/ui/declaration/index.js
- app/steps/ui/executors/invite/index.js
https://tools.hmcts.net/jira/browse/PRO-6539
Check exec list by name instead of email
```
[ ] Yes
[x] No
```
> PRO-6539: Content missing in tasklist when more than 1 additional executor is being declared

- app/steps/ui/payment/status/index.js
- test/unit/payment/testPaymentStatus.js
> PRO-6535: Payment success fix

- app/components/security.js
- app/config.js
- app/resources/en/translation/screeners/startapply.json
- app/routes.js
- app/steps/ui/signout/index.js
- test/unit/testSignOut.js
https://tools.hmcts.net/jira/browse/PRO-6601
Clear security cookie on signout
```
[ ] Yes
[X] No
```
> PRO-6601: Clear cookie on sign out

- app/steps/ui/coapplicant/agreepage/template.html
- app/steps/ui/coapplicant/allagreedpage/template.html
- app/steps/ui/coapplicant/declaration/template.html
- app/steps/ui/coapplicant/disagreepage/template.html
- app/steps/ui/coapplicant/startpage/template.html
- app/steps/ui/pin/resend/template.html
- app/steps/ui/pin/sent/template.html
- app/steps/ui/pin/signin/template.html
- app/views/includes/layout.html
https://tools.hmcts.net/jira/browse/PRO-6541
Hide navigation for coapplicant journey
```
[ ] Yes
[X] No
```
> PRO-6541: Hide navigation for coapplicant journey

- app/core/runners/UIStepRunner.js
- app/steps/ui/declaration/index.js
- app/wrappers/DetectDataChange.js
- test/data/complete-form.json
- test/unit/core/testUIStepRunner.js
- test/unit/testDeclaration.js
> Pro 6540 decrease from mult to single execs

- charts/probate-frontend/requirements.yaml
> added tag rpe-feature-toggle-api for chart

- app/views/widgets/addresslookup.html
> PRO-6548: postcode lookup fix

- charts/probate-frontend/Chart.yaml
> update version number

- app/steps/ui/executors/address/index.js
> PRO-6548: postcode lookup fix executors cya

- app.js
https://tools.hmcts.net/jira/browse/PRO-6706
Check for existing session on Redis before setting cookie
```
[ ] Yes
[X] No
```
> PRO-6706: Check for existing session on Redis before setting cookie

- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/requirements.yaml
> Fix feature toggle version

- app/assets/javascripts/document-upload.js
https://tools.hmcts.net/jira/browse/PRO-6769
Uploading document disappears
```
[ ] Yes
[x] No
```
> PRO-6769: Disable links as doc uploads

- app/steps/ui/payment/breakdown/index.js
- app/steps/ui/payment/status/index.js
- test/unit/payment/testPaymentStatus.js
> Pro 6811 pay after card details sign out

- app/steps/ui/payment/status/index.js
- test/unit/payment/testPaymentStatus.js
> merge from master

- test/accessibility/a11yTest.js
> Wla 23 bilingual declaration

- app/routes.js
https://tools.hmcts.net/jira/browse/PRO-6851
Check all applicants have agreed before routing
```
[ ] Yes
[X] No
```
> PRO-6851: Check all applicants have agreed before routing

- app/resources/cy/translation/common.json
- app/resources/cy/translation/language.json
- app/resources/cy/translation/will/codicilsnumber.json
- app/resources/en/translation/language.json
- app/steps/ui/executors/notified/template.html
- app/steps/ui/summary/includes/deceased.njk
- app/steps/ui/summary/index.js
- app/views/includes/help_details.html
- app/views/widgets/checkanswer.njk
> WLA-23: Escape some more strings

- app.js
- app/config.js
- app/middleware/multipleApplications.js
- app/routes.js
- app/utils/FormatUrl.js
- app/wrappers/Applicant.js
- app/wrappers/CcdCase.js
- app/wrappers/Documents.js
- app/wrappers/Executors.js
- app/wrappers/Payment.js
- test/accessibility/a11yTest.js
- test/component/assets/testAssetsOverseas.js
- test/component/common/testCommonContent.js
- test/component/copies/testCopiesOverseas.js
- test/component/copies/testCopiesSummary.js
- test/component/copies/testCopiesUk.js
- test/component/executors/testExecutorsInvitesSent.js
- test/component/payment/testPaymentBreakdown.js
- test/component/payment/testPaymentStatus.js
- test/component/testDocumentsPage.js
- test/component/testRedirectToDocuments.js
- test/component/testThankYouPage.js
- test/unit/middleware/testMultipleApplications.js
- test/unit/wrappers/testApplicantWrapper.js
- test/unit/wrappers/testCcdCaseWrapper.js
- test/unit/wrappers/testDocumentsWrapper.js
- test/unit/wrappers/testExecutorsWrapper.js
- test/unit/wrappers/testPaymentWrapper.js
- test/unit/wrappers/testWillWrapper.js
https://tools.hmcts.net/jira/browse/PRO-6550
Blacklist pages after Declaration until user declared
Blacklist pages after Payment until user paid
Blacklist pages after Submission until application complete
```
[ ] Yes
[X] No
```
> PRO-6550: Blacklist pages

- app/wrappers/Executors.js
https://tools.hmcts.net/jira/browse/PRO-6908
Fix bug on Tasklist section 3
```
[ ] Yes
[X] No
```
> PRO-6908: Fix bug on Tasklist section 3

- app/resources/en/translation/declaration.json
- test/data/legalDeclationHTML.html
- test/data/pacts/probate/invalidNoTitlelegalDeclaration.json
- test/data/pacts/probate/legalDeclaration.json
- test/data/pacts/probate/submitSingleExeDataClinet.json
https://tools.hmcts.net/jira/browse/PRO-6781
Amend Proceedings copy
```
[ ] Yes
[X] No
```
> PRO-6781: Amend Proceedings copy

- Jenkinsfile_CNP
- iisnode.yml
- web.config
> RO-6603: Removed server leaking info from HTTP response header

- app/assets/javascripts/dropzone.js
- package.json
- test/accessibility/a11yTest.js
- test/util/a11y.js
- yarn.lock
https://tools.hmcts.net/jira/browse/WLA-233
Upgrade Pa11y to latest version
```
[ ] Yes
[X] No
```
> [DO NOT MERGE] WLA-233: Upgrade Pa11y to latest version

- app/assets/javascripts/dropzone.js
- package.json
- test/accessibility/a11yTest.js
- test/util/a11y.js
- yarn.lock
Reverts hmcts/probate-frontend#1108
> Revert "[DO NOT MERGE] WLA-233: Upgrade Pa11y to latest version"

- Jenkinsfile_CNP
- app/resources/cy/translation/screeners/mentalcapacity.json
https://tools.hmcts.net/jira/browse/WLA-257
Amend Welsh copy
```
[ ] Yes
[X] No
```
> WLA-257: Amend Welsh copy

- Jenkinsfile_CNP
- app/config.js
- app/utils/FeesCalculator.js
https://tools.hmcts.net/jira/browse/PRO-7062
Update fees keywords
```
[ ] Yes
[x] No
```
> PRO-7062: Update fees keywords and move data to config

- app/steps/ui/payment/breakdown/index.js
- app/steps/ui/payment/breakdown/template.html
- app/steps/ui/payment/status/index.js
- test/unit/payment/testPaymentBreakdown.js
https://tools.hmcts.net/jira/browse/PRO-6842
Inconsistent decimalisation on payment summary page when Retry in 2 hours message is displayed
```
[ ] Yes
[x] No
```
> Pro 6842 amounts to 2 dp

- app/steps/ui/tasklist/includes/reviewAndConfirm.njk
https://tools.hmcts.net/jira/browse/PRO-7053
Show execs declaration statuses as undeclared if statuses not available
```
[ ] Yes
[X] No
```
> PRO-7053: Remove duplicate content

- app/resources/cy/translation/executors/currentname.json
- app/resources/cy/translation/executors/names.json
- app/resources/en/translation/executors/currentname.json
- app/resources/en/translation/executors/names.json
- app/steps/ui/executors/currentname/template.html
- app/steps/ui/executors/names/template.html
https://tools.hmcts.net/jira/browse/PRO-6072
Prompt user for execs middle names
```
[ ] Yes
[X] No
```
> PRO-6072: Prompt user for execs middle names

- app/steps/ui/coapplicant/declaration/template.html
- app/steps/ui/declaration/template.html
https://tools.hmcts.net/jira/browse/PRO-5079
Only have one H1 tag on Declaration and Coapplicant Declaration pages if application is bilingual.
```
[ ] Yes
[X] No
```
> PRO-5079: Only one H1 on Declaration and Coapplicant Declaration pages

- app/steps/ui/declaration/includes/download.html
- app/steps/ui/declaration/template.html
https://tools.hmcts.net/jira/browse/PRO-7090
Have different IDs for PDF download links on Declaration page
```
[ ] Yes
[X] No
```
> PRO-7090: IDs for PDF download links on Declaration page

- app/steps/ui/pin/resend/index.js
- test/component/pin/testPinResend.js
https://tools.hmcts.net/jira/browse/PRO-6919
Fix PIN resend
```
[ ] Yes
[X] No
```
> PRO-6919: Fix PIN resend

- test/end-to-end/saucelabs.conf.js
> PRO-5741: amendment for singleexecutorsPath

- Jenkinsfile_CNP
Mirror of https://github.com/hmcts/probate-caveats-frontend/pull/225
> Enabling AKS staging and disabling on AAT

- app/setupSecrets.js
- test/unit/testSetupSecrets.js
> fix secret mapping

- test/end-to-end/helpers/JSWait.js
- test/end-to-end/helpers/WebDriverHelper.js
- test/end-to-end/pages/applicant/address.js
- test/end-to-end/pages/dashboard/dashboard.js
- test/end-to-end/pages/deceased/address.js
- test/end-to-end/pages/executors/address.js
- test/end-to-end/pages/screeners/starteligibility.js
> PRO-5741: Fix singleExecutorsPath to work with Win10 IE11

- test/end-to-end/pages/deceased/anychildren.js
- test/end-to-end/pages/language/bilingualgrant.js
- test/end-to-end/pages/screeners/deathcertificate.js
- test/end-to-end/paths/generic/survey.js
- test/end-to-end/paths/intestacy/childPath.js
- test/end-to-end/paths/intestacy/spousePath.js
- test/end-to-end/paths/probate/singleExecutorsPath.js
> PRO-5741: upgrade e2e test

- test/end-to-end/paths/generic/survey.js
> further changes

- test/component/coapplicant/testCoApplicantAgreePage.js
- test/component/coapplicant/testCoApplicantAllAgreePage.js
- test/component/coapplicant/testCoApplicantDisagreePage.js
- test/component/coapplicant/testCoApplicantStartPage.js
- test/component/copies/testCopiesOverseas.js
- test/component/copies/testCopiesUk.js
- test/component/executors/testExecutorsAdditionalInvite.js
- test/component/executors/testExecutorsInvite.js
- test/component/pin/testPinResend.js
- test/component/pin/testPinSignIn.js
- test/component/screeners/testStartEligibilityPage.js
- test/util/TestWrapper.js
https://tools.hmcts.net/jira/browse/PRO-7283
Fix some component tests that shouldn't have been passing.
```
[ ] Yes
[X] No
```
> PRO-7283: Fix component tests

- app/assets/javascripts/address-fields-focus.js
https://tools.hmcts.net/jira/browse/PRO-7296
Move Address Fields Focus JS to correct folder
```
[ ] Yes
[X] No
```
> PRO-7296: Move Address Fields Focus JS to correct folder

- app/setupSecrets.js
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.preview.template.yaml
- charts/probate-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PRO-7290
Add GA Tracking Id secret
```
[ ] Yes
[X] No
```
> PRO-7290: Add GA Tracking Id secret

- test/end-to-end/paths/intestacy/childPath.js
https://tools.hmcts.net/jira/browse/PRO-7297
Fix Intestacy e2e journey
```
[ ] Yes
[X] No
```
> PRO-7297: Fix Intestacy e2e journey

- app/resources/cy/translation/common.json
- app/resources/en/translation/common.json
https://tools.hmcts.net/jira/browse/PRO-7200
Add GOV.UK suffix to page titles
```
[ ] Yes
[X] No
```
> PRO-7200: Add GOV.UK suffix to page titles

- app/steps/ui/applicant/address/template.html
- app/steps/ui/deceased/address/template.html
- app/steps/ui/executors/address/template.html
- app/views/widgets/addresslookup.html
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PRO-7207
Fix bug with Address form not expanding on IE and Edge when address picked from dropdown menu
```
[ ] Yes
[X] No
```
> PRO-7207: Fix address form on IE

- app.js
https://tools.hmcts.net/jira/browse/PRO-7313
Add Google Tag Manager to Content Security Policy whitelisting
```
[ ] Yes
[X] No
```
> PRO-7313: Add Google Tag Manager to CSP

- app/resources/cy/translation/addAlias.json
- app/resources/cy/translation/applicant/address.json
- app/resources/cy/translation/applicant/name.json
- app/resources/cy/translation/deceased/address.json
- app/resources/cy/translation/deceased/details.json
- app/resources/cy/translation/deceased/dob.json
- app/resources/cy/translation/deceased/dod.json
- app/resources/cy/translation/deceased/name.json
- app/resources/cy/translation/deceased/otherNames.json
- app/resources/cy/translation/executors/address.json
- app/resources/cy/translation/executors/currentname.json
- app/resources/cy/translation/executors/names.json
- app/resources/cy/translation/iht/paper.json
- app/resources/cy/translation/iht/value.json
- app/resources/cy/translation/iht/valueassetsoutside.json
- app/resources/cy/translation/language.json
- app/resources/cy/translation/removeAlias.json
- app/resources/cy/translation/will/codicilsnumber.json
https://tools.hmcts.net/jira/browse/PRO-7201
Add Welsh translations
```
[ ] Yes
[X] No
```
> PRO-7201: Add Welsh translations

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/PRO-7373
Update webchat dependency
```
[ ] Yes
[X] No
```
> PRO-7373: Update webchat dependency

- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PRO-7216
Remove EQUALITY_URL as it's defined in flux.
```
[ ] Yes
[x] No
```
> PRO-7216 Remove equality URLs

- app/middleware/completeEqualityTask.js
Remove PCQ ID if PCQ is down.
```
[ ] Yes
[ ] No
```
> Remove PCQ ID if PCQ is down

- app/middleware/completeEqualityTask.js
- app/services/FormData.js
- charts/probate-frontend/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/PRO-7216
Update to fix authentication when saving pcq id for the first time.
```
[ ] Yes
[x] No
```
> Pro 7216 fix authentication when calling pcq

- app/views/includes/error_summary.html
- app/views/includes/scripts_ga_1.html
> PRO-7428: adding data layer script

- app/assets/sass/patterns/_header.scss
> PRO-1234: header link colour fix

- app/core/steps/Step.js
- app/views/includes/help_details.html
- app/views/includes/scripts.html
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/requirements.yaml
- test/unit/copies/testCopiesOverseas.js
- test/unit/copies/testCopiesUk.js
- test/unit/core/testEligibilityValidationStep.js
- test/unit/deceased/testDeceasedAddress.js
- test/unit/deceased/testDeceasedAlias.js
- test/unit/executors/testExecutorsAdditionalInviteSent.js
- test/unit/pin/testPinResend.js
- test/unit/pin/testPinSent.js
- test/unit/screeners/testApplicantExecutor.js
- test/unit/screeners/testDeathCertificate.js
- test/unit/screeners/testDeceasedDomicile.js
- test/unit/screeners/testDiedAfterOctober2014.js
- test/unit/screeners/testIhtCompleted.js
- test/unit/screeners/testMentalCapacity.js
- test/unit/screeners/testOtherApplicants.js
- test/unit/screeners/testRelatedToDeceased.js
- test/unit/screeners/testWillLeft.js
- test/unit/screeners/testWillOriginal.js
- test/unit/testDashboard.js
- test/unit/testSummary.js
- test/unit/will/testWillCodicils.js
- test/unit/will/testWillCodicilsNumber.js
Hide webchat on Welsh
```
[ ] Yes
[X] No
```
> Hide webchat on Welsh

- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.yaml
https://tools.hmcts.net/jira/browse/PCQ-273
Chart changes for PCQ-273 - PR #1213: Add pcq token key to secret list.
```
[ ] Yes
[x] No
```
> PCQ-273: Chart changes

- app/steps/ui/declaration/index.js
- test/unit/testDeclarationPost.js
https://tools.hmcts.net/jira/browse/PRO-7777
including logs for the declaration submission 
```
[ ] Yes
[X] No
```
> Pro 7750 declaration logs

- app/middleware/multipleApplications.js
- app/steps/ui/declaration/index.js
https://tools.hmcts.net/jira/browse/PRO-7777
```
[ ] Yes
[X] No
```
> adding logs to see the cases retrieved

- package.json
> enable contract tests in pipeline

- app/routes.js
https://tools.hmcts.net/jira/browse/DTSPB-259
Update routes.js to have perftest so that right endpoints could be hit 
```
[ ] Yes
[X] No
```
> DTSPB-259 Update routes.js to have perftest

- app/core/initSteps.js
- app/routes.js
https://tools.hmcts.net/jira/browse/DTSPB-124
Load steps on boot rather than on every requests
```
[ ] Yes
[x] No
```
> load steps at start up rather than on every request

- charts/probate-frontend/values.preview.template.yaml
- test/config.js
- test/end-to-end/helpers/TestConfigurator.js
- test/end-to-end/pages/equalityanddiversity/startpage.js
- test/end-to-end/pages/steps.js
- test/end-to-end/paths/probate/singleExecutorsPath.js
https://tools.hmcts.net/jira/browse/DTSPB-181
Enable launch darkly in preview
```
[ ] Yes
[x] No
```
> Dtspb 181 enable launchdarkly in pr

- charts/probate-frontend/values.aat.template.yaml
> Enable ld on aat

- test/util/TestWrapper.js
https://tools.hmcts.net/jira/browse/DTSPB-683
Enable component tests to run on different journeys
```
[ ] Yes
[x] No
```
> Parameterise test wrapper

- Jenkinsfile_CNP
- README.md
- test/config.js
- test/end-to-end/helpers/LaunchDarkly.js
- test/end-to-end/helpers/TestConfigurator.js
- test/end-to-end/paths/probate/singleExecutorsPath.js
https://tools.hmcts.net/jira/browse/DTSPB-672
Enable Launch Darkly for e2e tests
```
[ ] Yes
[x] No
```
> Launch darkly working on local e2e

- test/config.js
- test/end-to-end/helpers/TestConfigurator.js
https://tools.hmcts.net/jira/browse/DTSPB-724
Fix timeout issue on e2e tests running LaunchDarkly
```
[ ] Yes
[x] No
```
> Close LD stream when tests finished

- config/dev.yaml
Remove test ld sdk key
Remove test ld sdk key
```
[ ] Yes
[x] No
```
> Remove test ld sdk key

- docker-compose.yml
https://tools.hmcts.net/jira/browse/DTSPB-851
change for payment api docker config
```
[ ] Yes
[ X ] No
```
> DTSPB-851 fix for  payment api

- app/steps/ui/declaration/index.js
https://tools.hmcts.net/jira/browse/DTSPB-931
removing the logger from declaration step
```
[ ] Yes
[x] No
```
> PRO-931: remove the logger

- app/steps/ui/deceased/foreigndeathcerttranslation/template.html
https://tools.hmcts.net/jira/browse/DTSPB-939
Change foreign death cert page so radio buttons on different lines
```
[ ] Yes
[x] No
```
> Foreign death cert radio buttons on different lines

- app/resources/cy/translation/deceased/deathcertificate.json
- app/resources/cy/translation/deceased/diedengorwales.json
- app/resources/cy/translation/deceased/englishforeigndeathcert.json
- app/resources/cy/translation/deceased/foreigndeathcerttranslation.json
- app/resources/cy/translation/documents_new_death_cert_flow.json
- app/resources/cy/translation/screeners/deathcertificate.json
- app/resources/cy/translation/screeners/deathcertificateinenglish.json
- app/resources/cy/translation/screeners/deathcertificatetranslation.json
- app/resources/cy/translation/stoppage.json
- app/resources/en/translation/deceased/deathcertificate.json
- app/resources/en/translation/deceased/foreigndeathcerttranslation.json
- app/resources/en/translation/documents_new_death_cert_flow.json
- app/resources/en/translation/screeners/deathcertificateinenglish.json
- app/resources/en/translation/screeners/deathcertificatetranslation.json
- app/steps/ui/deceased/englishforeigndeathcert/template.html
- test/component/deceased/testDeathCertificate.js
- test/component/deceased/testDiedEngOrWales.js
- test/component/deceased/testEnglishForeignDeathCert.js
- test/component/deceased/testForeignDeathCertTranslation.js
- test/unit/testDocumentsPage_new_death_cert-flow.js
- test/util/TestWrapper.js
https://tools.hmcts.net/jira/browse/DTSPB-745
Add welsh translation for new death cert flow
```
[ ] Yes
[x] No
```
> Add welsh content

- Jenkinsfile_nightly
- test/end-to-end/helpers/JSWait.js
- test/end-to-end/saucelabs.conf.js
Sub-task: https://tools.hmcts.net/jira/browse/DTSPB-1013
Parent Task: https://tools.hmcts.net/jira/browse/DTSPB-999
This change:
- fixes crossbrowser reporting in Nightly pipeline
- improves environment variable handling in Nightly pipeline
- fixes a test step causing the nightly crossbrowser tests to hang indefinitely, meaning the test reports never generate
```
[ ] Yes
[x] No
```
> DTSPB-999: Fix crossbrowser reporting

- charts/probate-frontend/Chart.yaml
- package.json
https://tools.hmcts.net/jira/browse/DTSPB-1095
Change FE E2E to check LD for FT values
```
[ ] Yes
[x] No
```
> Run launch darkly config for e2e

- test/end-to-end/pages/deceased/diedengorwales.js
https://tools.hmcts.net/jira/browse/DTSPB-1170
Fix FE e2e tests for new death cert flow. 
```
[ ] Yes
[x] No
```
> Fix error in diedengorwales page

- test/end-to-end/pages/tasklist/tasklist.js
- test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
https://tools.hmcts.net/jira/browse/DTSPB-1170
Fix intestacy spouse journey
```
[ ] Yes
[x] No
```
> Fix intestacy spouse path

- test/end-to-end/paths/probate/multipleExecutors.js
https://tools.hmcts.net/jira/browse/DTSPB-1170
Add useNewDeathCertFlow to multipleExecutors.js e2e test to fix the test in the overnight pipeline.
```
[ ] Yes
[x] No
```
> DTSPB-1170: Add useNewDeathCertFlow to multipleExecutors.js e2e test

- app.js
https://tools.hmcts.net/jira/browse/DTSPB-1201
Track radio button selections in Data layer
```
[ ] Yes
[x] No
```
> Add hash to contentSecurityPolicy

- app/featureToggles.js
https://tools.hmcts.net/jira/browse/DTSPB-1212
Move ft check
```
[ ] Yes
[x] No
```
> Check FT on death-certificate page

- app/resources/cy/translation/copies/overseas.json
- app/resources/cy/translation/copies/uk.json
https://tools.hmcts.net/jira/browse/DTSPB-895
welsh translation forr copies pages
```
[x] Yes
[ ] No
```
> PRO-895: upgrade the copies welsh translation

- .github/renovate.json
DTSPB-1408
Update missing readiness and renovate.json
DTSPB-1408
Update missing readiness and renovate.json
```
[ ] Yes
[ x] No
```
> PRO-1048: adding renovate.json

- .gitignore
- config/default.yaml
- config/dev.yaml
PRO-1699: adding back the hardcoded token
PRO-1699: adding back the hardcoded token
```
[ ] Yes
[x] No
```
> PRO-1699: adding back the hardcoded token

- app/assets/javascripts/avaya-webchat.js
DTSPB-1960: default to closed when there is issue
DTSPB-1960: default to closed when there is issue
```
[ ] Yes
[ ] No
```
> DTSPB-1960: default to closed when there is issue

- app/resources/en/translation/common.json
DTSPB-1960: update content changes
DTSPB-1960: update content changes
```
[ ] Yes
[ ] No
```
> DTSPB-1960: update content changes

- app/views/includes/scripts.html
DTSPB-2027: update webchat sha value
DTSPB-2027: update webchat sha value
```
[ ] Yes
[x] No
```
> DTSPB-2027: update webchat sha value

- Jenkinsfile_nightly
JIRA link (if applicable)
DTSPB-1899
Change description
change time of nightly run for probate front end
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[X ] No
> Dtspb 1899 change e2e running time

- package.json
- yarn.lock
no jira ticket
npm audit to fix vunerability issue
```
[ ] Yes
[x] No
```
> npm audit to fix vunerability issue

- Jenkinsfile_CNP
JIRA link (if applicable)
https://tools.hmcts.net/jira/browse/DTSPB-2020
Change description
code changes to sync all branches to master with every deployment
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[ X ] No
> DTSPB-2020 Sync All env to master with every commit

- Jenkinsfile_CNP
> Remove commented code for fresh commit

- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.preview.template.yaml
- charts/probate-frontend/values.yaml
DTSPB-2036: update chart version for avaya webchat
DTSPB-2036: update chart version for avaya webchat
```
[ ] Yes
[x] No
```
> DTSPB-2036: update chart version for avaya webchat

- test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
- test/end-to-end/saucelabs.conf.js
https://tools.hmcts.net/jira/browse/DTSPB-2283
- Fix seemingly randomly failing XB tests.
```
[ ] Yes
[x] No
```
> DTSPB-2283 - Fix failing XB tests

- Jenkinsfile_nightly
- config/test.yaml
- package.json
- test/crossbrowser/supportedBrowsers.js
- test/end-to-end/pages/coapplicant/declaration.js
- test/end-to-end/pages/executors/invite.js
DTSPB-2353 - Update FE Jenkins Nightly pipeline to execute current functional UI tests
The is change to add the functional test to the Jenkins nightly pipeline and also update some failing tests 
```
[ ] Yes
[x ] No
```
> DTSPB-2353-Updated nightly and Multi exec file

- package.json
- yarn.lock
N/A
Component updates
```
[ ] Yes
[X] No
```
> fix vulnerabilities

- config/default.yaml
- package.json
- test/api/launchDarkly.js
https://tools.hmcts.net/jira/browse/DTSPB-2424
Feature toggle for excepted estates
```
[ ] Yes
[x] No
```
> DTSPB-2424: Test for expected estates feature toggle

- app/middleware/completeEqualityTask.js
https://tools.hmcts.net/jira/browse/DTSPB-2466
Correct missing auth token
```
[ ] Yes
[X] No
```
> Correct auth token issue for pcq call

- test/java/build.gradle
upgrade fortify version 
```
[ ] Yes
[X ] No
```
> Remove INFO Logs for Fortify

- config/test-dk.yaml
- package.json
https://tools.hmcts.net/jira/browse/DTSPB-2339
Add config for launch darkly for fullfunctional test
```
[ ] Yes
[X] No
```
> Add config for launch darkly for fullfunctional test

- app/resources/cy/translation/declaration.json
- app/resources/en/translation/declaration.json
- app/steps/ui/declaration/includes/estate.html
- app/steps/ui/declaration/index.js
- app/steps/ui/declaration/template.html
- app/utils/ProbateDeclarationFactory.js
- test/component/testDeclarationIntestacy.js
- test/component/testDeclarationPageMultipleApplicants.js
- test/component/testDeclarationPageSingleApplicant.js
- test/unit/utils/testProbateDeclarationFactory.js
https://tools.hmcts.net/jira/browse/DTSPB-2488
EE legal statement
```
[ ] Yes
[x] No
```
> DTSPB-2488: EE legal declaration

- app/middleware/multipleApplications.js
DTSPB-2430
Fix new user case creation
```
[ ] Yes
[ ] No
```
> DTSPB-2430: Fix new user case creation

- app/resources/cy/translation/iht/deceasedlatespousecivilpartner.json
- app/resources/cy/translation/iht/estateform.json
- app/resources/cy/translation/iht/estatevalued.json
- app/resources/cy/translation/iht/ihtestatevalues.json
- app/resources/cy/translation/iht/probateestatevalues.json
- app/resources/cy/translation/iht/unusedallowanceclaimed.json
https://tools.hmcts.net/jira/browse/DTSPB-2492
Welsh tranlations
```
[ ] Yes
[ ] No
```
> DTSPB-2492: Welsh translations

- app/journeys/intestacy.js
- test/component/deceased/testDeathCertificate.js
- test/component/deceased/testEnglishForeignDeathCert.js
- test/component/deceased/testForeignDeathCertTranslation.js
https://tools.hmcts.net/jira/browse/DTSPB-2437
EE intestacy journey
```
[ ] Yes
[x] No
```
> DTSPB-2437 ee intestacy journey

- app/journeys/intestacy.js
https://tools.hmcts.net/jira/browse/DTSPB-2437
Correct intestacy journey
```
[ ] Yes
[ ] No
```
> DTSPB-2437: correct intestacy journey

- app/resources/cy/translation/documents.json
- app/resources/en/translation/documents.json
- app/steps/ui/documents/index.js
- app/steps/ui/documents/template.html
- test/component/testDocumentsPage.js
- test/unit/testDocumentsPage.js
https://tools.hmcts.net/jira/browse/DTSPB-2433
add send docs text if iht form is 207
```
[ ] Yes
[x] No
```
> DTSPB-2433 add send docs iht 207 text

- app/resources/en/translation/screeners/eeestatevalued.json
https://tools.hmcts.net/jira/browse/DTSPB-2509
typo on ee estate valued screener
```
[ ] Yes
[x] No
```
> DTSPB-2509 ee estate valued typo

- app/resources/en/translation/iht/ihtestatevalues.json
https://tools.hmcts.net/jira/browse/DTSPB-2547
Temporary hint text
```
[ ] Yes
[x ] No
```
> DTSPB-2547: Add temporary-hint-text

- app/components/error.js
- app/resources/cy/translation/declaration.json
- app/resources/en/translation/declaration.json
https://tools.hmcts.net/jira/browse/DTSPB-2549)
Fix validation message
```
[ ] Yes
[ ] No
```
> DTSPB_2549: Fix validation error message

- package.json
- yarn.lock
N/A
Updates
```
[ ] Yes
[ ] No
```
> Fix dependency issue

- app/resources/cy/translation/screeners/starteligibility.json
- app/resources/en/translation/screeners/starteligibility.json
- test/service-stubs/feesApi.js
https://tools.hmcts.net/jira/browse/DTSPB-2445
change hardcoded values of application
```
[ ] Yes
[x] No
```
> DTSPB-2445 amend value of app to 273 on all hardcoded values

- config/default.yaml
- test/unit/services/testFees.js
- test/unit/services/testFeesLookup.js
- test/unit/utils/testFeesCalculator.js
https://tools.hmcts.net/jira/browse/DTSPB-2562
update keyword and application type
```
[ ] Yes
[X ] No
```
> DTSPB-2562 Change keywords for citizen journey

- package.json
- test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
comment the full functional 
```
[ ] Yes
[ X ] No
```
> Comment the full functional as taking very long to execute

- bin/run-yarn-audit.sh
- charts/probate-frontend/Chart.yaml
- package.json
- yarn.lock
> DTSPB-2600: Fix failing dep for probate fe nightly

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/DTSPB-2675
```
[ ] Yes
[ ] No
```
> DTSPB-2675: minimist dependency warning

- app/steps/ui/pin/signin/index.js
- test/unit/pin/testSignIn.js
https://tools.hmcts.net/jira/browse/DTSPB-2670
Do not clear declaration checkbox when signing in as co-exec
```
[ ] Yes
[x] No
```
> DTSPB-2670 do not clear declaration checkbox when signing in as co-exec

- app/resources/cy/translation/screeners/willleft.json
- app/resources/cy/translation/screeners/willoriginal.json
- app/resources/en/translation/screeners/willleft.json
- app/resources/en/translation/screeners/willoriginal.json
- app/steps/ui/screeners/willleft/template.html
- app/steps/ui/screeners/willoriginal/template.html
- config/default.yaml
- test/component/screeners/testWillOriginal.js
fixed hints wording on screeners
> DTSPB-2555: fixed hint wording

- yarn.lock
fix vulnerability
```
[ ] Yes
[x] No
```
> amend yarn.lock

- yarn.lock
https://tools.hmcts.net/jira/browse/DTSPB-2730
fix dep issue
```
[ ] Yes
[ ] No
```
> DTSPB-2730 fix dep issue

- app/utils/DocumentPageUtil.js
- test/unit/services/testCoverSheetPdf.js
https://tools.hmcts.net/jira/browse/DTSPB-2729
```
[ ] Yes
[x] No
```
> DTSPB-2729  fix Send Documents Item at Written Wishes

- Jenkinsfile_CNP
> DTSPB-2760: Fix nightly full functional on PRs

- app/steps/ui/executors/invite/index.js
- test/unit/executors/testExecutorsInvite.js
https://tools.hmcts.net/jira/browse/DTSPB-2793
fix executor invite email sent flag
```
[ ] Yes
[ ] No
```
> DTSPB-2793: fix executor invite email sent flag

- app/steps/ui/executors/additionalinvite/index.js
- app/steps/ui/executors/contactdetails/index.js
- app/wrappers/Executors.js
- test/component/testDeclarationPageMultipleApplicants.js
- test/unit/executors/testExecutorsContactDetails.js
- test/unit/utils/testAdditionalExecutorInvite.js
- test/unit/wrappers/testExecutorsWrapper.js
https://tools.hmcts.net/jira/browse/DTSPB-2786
check executor.inviteId as well as executor.emailSent
```
[ ] Yes
[ ] No
```
> DTSPB-2793: check executor.inviteId as well as executor.emailSent

- test/unit/executors/testExecutorsAdditionalInvite.js
https://tools.hmcts.net/jira/browse/DTSPB-2843
Add test
```
[ ] Yes
[ ] No
```
> DTSPB-2843: Add test

- app.js
- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/DTSPO-5664
```
[ ] Yes
[ ] No
```
> DTSPO-5664: Fix Appinsights Configuration

- charts/probate-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPB-2943
upgrade chart version 
```
[ ] Yes
[x ] No
```
> DTSPB-2943 - upgrade nodejs chart

- app/resources/cy/translation/common.json
- app/resources/en/translation/common.json
DTSPB-2942 times
```
[ ] Yes
[x] No
```
> Dtspb 2942

- app/middleware/completeEqualityTask.js
- app/steps/ui/equality/createToken.js
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.preview.template.yaml
- test/service-stubs/equalityAndDiversityHealth.js
- test/unit/testEquality.js
https://tools.hmcts.net/jira/browse/DTSPB-1858
Updating older cbc algorithm, as it has a security vulnerability against it in SonarCloud.
```
[ ] Yes
[X ] No
```
> Dtspb 1858 update pcq token algorithm

- app/assets/javascripts/avaya-webchat-2.js
https://tools.hmcts.net/jira/browse/DTSPB-2977
revert EWT changes
```
[ ] Yes
[x] No
```
> DTSPB-2977 revert ewt changes

- app/routes.js
Add preview and local envs to testing support route
```
[ ] Yes
[ ] No
```
> DTSPB-2913: Add preview and local envs to testing support route

- test/unit/testRoutes.js
Unit test
```
[ ] Yes
[ ] No
```
> DTSPB-2913: unit test

- test/unit/testRoutes.js
Unit test
```
[ ] Yes
[ ] No
```
> DTSPB-2913: update unit test

- sonar-project.properties
fix sonar coverage setup
```
[ ] Yes
[ ] No
```
> DTSPB-2913: fix sonar coverage setup

- test/end-to-end/helpers/TestConfigurator.js
- test/end-to-end/pages/declaration/declaration.js
- test/end-to-end/pages/equalityanddiversity/completedpage.js
- test/end-to-end/pages/equalityanddiversity/startpage.js
- test/end-to-end/pages/executors/address.js
- test/end-to-end/pages/executors/alias.js
- test/end-to-end/pages/executors/contactdetails.js
- test/end-to-end/pages/executors/notified.js
- test/end-to-end/pages/executors/roles.js
- test/end-to-end/pages/executors/whendied.js
- test/end-to-end/pages/executors/whodied.js
- test/end-to-end/paths/probate/multipleExecutors.EE.no.js
- test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
- test/end-to-end/paths/probate/multipleExecutors.js
> DTSPB-2913 e2e test fix for multiexecutors.js

- charts/probate-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSSE-2784
```
[ ] Yes
[ ] No
```
> New chart released for DNS update in Demo

- Jenkinsfile_CNP
- package.json
- test/end-to-end/paths/generic/survey.test.js
- test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
- test/end-to-end/paths/intestacy/intestacy.en.test.js
- test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
- test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
- test/end-to-end/paths/other/creditCardPaymentCancellation.js
- test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
- test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
- test/end-to-end/paths/probate/multipleExecutors.EE.no.js
- test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
- test/end-to-end/paths/probate/multipleExecutors.js
- yarn.lock
https://tools.hmcts.net/jira/browse/DTSPB-3304
- See JIRA
```
[ ] Yes
[ ] No
```
> DTSPB-3304 - Add new tag for pr nightly

- .github/renovate.json
https://tools.hmcts.net/jira/browse/DTSPB-3308
> DTSPB-3308 - One PR per dependency in renovate

- app/steps/ui/deceased/details/template.html
- app/steps/ui/deceased/dob/template.html
- app/steps/ui/deceased/dod/template.html
- app/steps/ui/will/codicilshasvisibledamage/template.html
- app/steps/ui/will/willhasvisibledamage/template.html
- test/end-to-end/pages/deceased/details.js
- test/end-to-end/pages/deceased/dob.js
- test/end-to-end/pages/deceased/dod.js
- test/end-to-end/pages/will/codicilsdamage.js
- test/end-to-end/pages/will/willdamage.js
https://tools.hmcts.net/jira/browse/DTSPB-3260
Updated so when error message is clicked, it takes the user to the correct section of screen, and keeps Other free textbox if it is checked without entering info and clicking continue. 
```
[ ] Yes
[x] No
```
> Dtspb 3260

- app/resources/cy/translation/iht/method.json
- app/resources/en/translation/iht/method.json
- app/steps/ui/iht/method/index.js
- app/steps/ui/iht/method/template.html
- package.json
- test/unit/iht/testIhtMethod.js
- test/unit/middleware/testDocumentUpload.js
- yarn.lock
https://tools.hmcts.net/jira/browse/DTSPB-3241
```
[ ] Yes
[ ] No
```
> DTSPB-3241 - Add content to indicate IHT service is closed (v2)

- Jenkinsfile_nightly
DTSPB-3211
```
[ ] Yes
[x] No
```
> DTSPB-3211 fix after to afterAlways or afterSuccess

- Jenkinsfile_CNP
- README.md
- package.json
- test/accessibility/a11yTest.js
- test/end-to-end/helpers/GeneralHelpers.js
- test/end-to-end/paths/intestacy/intestacy.en.test.EE.no.js
- test/end-to-end/paths/intestacy/intestacy.en.test.EE.yes.js
- test/end-to-end/paths/intestacy/intestacy.en.test.js
- test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.no.js
- test/end-to-end/paths/intestacy/intestacy.spouse.en.test.EE.yes.js
- test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
- test/end-to-end/paths/other/creditCardPaymentCancellation.js
- test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.no.js
- test/end-to-end/paths/probate/gopSingleExecutor.en.test.EE.yes.js
- test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
- test/end-to-end/paths/probate/multipleExecutors.EE.no.js
- test/end-to-end/paths/probate/multipleExecutors.EE.yes.js
- test/end-to-end/paths/probate/multipleExecutors.js
https://tools.hmcts.net/jira/browse/DTSPB-3372
- See JIRA
```
[ ] Yes
[ ] No
```
> DTSPB-3372 - Add option to only run English tests for e2e nightly run

- app.js
> DTSPB-3433 - Check whether we need useAuth and useHttps

- app/resources/cy/translation/common.json
https://tools.hmcts.net/jira/browse/DTSPB-3691
```
[ ] Yes
[x ] No
```
> DTSPB-3691 Added walesh translation on survey link

- .github/renovate.json
https://tools.hmcts.net/jira/browse/DTSPB-3839
```
[ ] Yes
[ x] No
```
> DTSPB 3839  remove renovate automerge 

- charts/probate-frontend/Chart.yaml
> New nodejs Chart 3.0.1

- app/steps/ui/static/avaya-webchat/template.html
- app/views/includes/head.html
> DTSPB-3758 Force update CSS

- app/components/step-utils.js
https://tools.hmcts.net/jira/browse/DTSPB-3980
```
[ ] Yes
[x] No
```
> DTSPB-3980 Remove back link from Thank you page

- app/steps/ui/iht/uniqueprobatecode/schema.json
- app/steps/ui/iht/uniqueprobatecode/template.html
https://tools.hmcts.net/jira/browse/DTSPB-4012
Added Max allowed no.
```
[ ] Yes
[X] No
```
> DTSPB-3970 Fixed allowed number in Unique code

- app/steps/ui/copies/summary/index.js
- sonar-project.properties
- test/unit/copies/testCopiesSummary.js
https://tools.hmcts.net/jira/browse/DTSPB-4040
```
[ ] Yes
[x ] No
```
> DTSPB-4033  Adding Google Tag Manager to /copies-summary page on Probate Journey

- app/core/runners/UIStepRunner.js
- app/resources/cy/translation/common.json
- app/resources/en/translation/common.json
- charts/probate-frontend/Chart.yaml
- test/component/copies/testCopiesUk.js
- test/component/deceased/testDivorcePlace.js
- test/component/deceased/testOtherNames.js
- test/component/executors/testExecutorCurrentName.js
- test/component/executors/testExecutorCurrentNameReason.js
- test/component/executors/testExecutorsAdditionalInvite.js
- test/component/executors/testExecutorsAdditionalInviteSent.js
- test/component/executors/testExecutorsContactDetails.js
- test/component/executors/testExecutorsDealing.js
- test/component/executors/testExecutorsNames.js
- test/component/executors/testExecutorsUpdateInvite.js
- test/component/executors/testExecutorsWhenDied.js
- test/component/executors/testExecutorsWhoDied.js
- test/component/executors/testNotified.js
- test/component/executors/testRoles.js
- test/component/testDeclarationIntestacy.js
- test/component/testDeclarationPageSingleApplicant.js
- test/unit/core/testUIStepRunner.js
https://tools.hmcts.net/jira/browse/DTSPB-3463
```
[ ] Yes
[x] No
```
> DTSPB-3463: Added logic to display Error component on 400 error

- bin/run-crossbrowser-tests.sh
> DTSPB-2849 : Remove microsoft browser from shell command

- app/steps/ui/iht/hmrcletter/index.js
https://tools.hmcts.net/jira/browse/DTSPB-4061
```
[ ] Yes
[ x] No
```
> DTSPB-4061 fix IHT400 & HMRC Letter No 504 issue

- app/setupSecrets.js
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.preview.template.yaml
- charts/probate-frontend/values.yaml
- config/custom-environment-variables.yaml
- config/default.yaml
- server.js
https://tools.hmcts.net/jira/browse/DTSPB-3908
```
[ ] Yes
[x] No
```
> DTSPB-3908 change to AppInsight_connection_String

- test/java/build.gradle
[DTSPB-4073](https://tools.hmcts.net/jira/browse/DTSPB-4073)
```
[ ] Yes
[x] No
```
> Nightly dev

- test/end-to-end/pages/payment/govukpayment.js
https://tools.hmcts.net/jira/browse/DTSPB-4083
```
[ ] Yes
[ ] No
```
> Fix FE Nightly failure for e2e tests on Payment button

- app/assets/locales/avaya-webchat/en-cy/locale_en-GB.json
- app/resources/cy/translation/common.json
> Dtspb 3810 webchat welsh

- package.json
- yarn.lock
https://tools.hmcts.net/jira/browse/DTSPB-4114
```
[ ] Yes
[ x] No
```
> DTSPB-4114 updated the express package .

- charts/probate-frontend/Chart.yaml
https://tools.hmcts.net/jira/browse/DTSPB-4118
> DTSPB-4118 new chart version for enabling hpa

- package.json
- yarn.lock
> DTSPB-4158: Formidable CVE

- Jenkinsfile_nightly
[DTSPB-4194](https://tools.hmcts.net/jira/browse/DTSPB-4194)
```
[ ] Yes
[x] No
```
> DTSPB-4194 change nightly execution time

- app/steps/ui/applicant/address/template.html
- app/steps/ui/deceased/address/template.html
- app/steps/ui/executors/address/template.html
- app/views/includes/two_thirds_form.html
[DTSPB-4377](https://tools.hmcts.net/jira/browse/DTSPB-4377)
```
[ ] Yes
[x] No
```
> DTSPB-4377 fix GTM submit element order

- package.json
- yarn.lock
> DTSPB-4420: Fix Acorn CVE

- app/resources/cy/translation/citizenshub.json
- app/resources/en/translation/citizenshub.json
- app/steps/ui/citizenshub/template.html
Banner on CitizenHub
```
[ ] Yes
[X] No
```
> Notification banner on CitizenHub page

- Jenkinsfile_nightly
update nightly run time
```
[ ] Yes
[x] No
```
> update nightly run time

- package.json
- yarn.lock
Reverts hmcts/probate-frontend#2367
> Revert "Update dependency file-type"

- app/core/runners/UIStepRunner.js
- app/steps/ui/summary/includes/executors-others-not-applying.njk
See [DTSPB-4713](https://tools.hmcts.net/jira/browse/DTSPB-4713)
Adds case information if present to logs to help identify cases which hit errors.
Changes which variable is used in the exec-not-applying template to prevent template failures.
```
[ ] Yes
[x] No
```
> DTSPB-4713 Resolve issues with templates preventing case submission

- app/services/PinNumber.js
- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.preview.template.yaml
- test/component/pin/testPinResend.js
- test/contract/generatepin/testGeneratePin.js
- test/contract/pact/probate/PinNumberClient.spec.js
- test/unit/services/testPinNumber.js
> Dtspb 4664 do not get with params

- charts/probate-frontend/Chart.yaml
Update chart to use oci
```
[ ] Yes
[x] No
```
> Update chart to use oci

- app/resources/cy/translation/common.json
- app/resources/en/translation/common.json
See [DTSPB-4909](https://tools.hmcts.net/jira/browse/DTSPB-4909)
```
[ ] Yes
[ ] No
```
> DTSPB-4909 update webchat strings.

- charts/probate-frontend/Chart.yaml
- charts/probate-frontend/values.preview.template.yaml
- charts/probate-frontend/values.yaml
DTSPB-4937
move bitnami chart to hmcts acr
```
[ ] Yes
[x] No
```
> DTSPB-4937 move bitnami chart to hmcts acr
