app/views/widgets/checkanswer.html

https://tools.hmcts.net/jira/browse/PRO-1123
After much discussion and researching, the desired solution is now to
remove the hidden text from our links on Check Your Answers page, as per
the approved Divorce solution.
```
[ ] Yes
[x] No
```

PRO-1123: Remove hidden text from links on Check Your Answers

---

app/config.js
app/healthcheck.js
test/unit/testHealthcheck.js

https://tools.hmcts.net/jira/browse/PRO-2595
- Tidy healthcheck code
- Return git hash from the /health endpoint and export method and variables to use in unit tests
- Tidy unit tests and add unit tests for the getServiceHealthUrl() method
```
[ ] Yes
[x] No
```

PRO-2595 - CNP: Add smoke test for probate fronted to get git hash in health end point

---

app/resources/en/translation/documents.json
app/steps/ui/documents/index.js
app/steps/ui/documents/template.html
app/steps/ui/payment/status/index.js
app/wrappers/Documents.js
app/wrappers/Will.js
test/component/testDocumentsPage.js
test/service-stubs/submit.js
test/unit/testDocumentsWrapper.js
test/unit/testWillWrapper.js
test/util/TestWrapper.js

https://tools.hmcts.net/jira/browse/PRO-2216
**Add method to the will wrapper**
- Add codicilsNumber() to return the number of codicils on the application
- Add unit tests for codicilsNumber() method and improve other unit tests
**Add documents wrapper**
- Add registryAddress() method to get the address of the registry that the documents for the current application need to be sent to
- Add unit tests for registryAddress() method
**Update data returned from the submit stub**
- Change from submissionReference string to an object with the following properties
- submissionReference
- registrySequenceNumber
- address
- Tidy code
**Update the registry address that is displayed on the documents page**
- Add logic to dsplay either the specified registry address or the default address if an …

PRO-2216 - Multiple registries - Display Relevant registry address on the documents page

---

app/steps/ui/executors/currentname/index.js
app/wrappers/Executors.js
test/unit/testExecutorsWrapper.js

We need to check if executors with another name have the other name set. If no executors name another name and hence return an empty list then the every function will return true.
```
[ ] Yes
[x] No
```

Improve the validation check for executors with another name

---

README.md
app/config.js
package.json
test/data/find-address.json
test/service-stubs/find-address.js

**Create a stub for the address lookup**
Currently the address lookup doesn't work locally and we don't want to have to rely on an external service for this to work so this creates a stub to return an address.
- Enter `VALID` in the postcode field to return an address
- Enter anything else to return an error
```
[ ] Yes
[x] No
```

Create a stub for the address lookup

---

app/steps/ui/executors/address/index.js
test/unit/testExecutorAddress.js

https://tools.hmcts.net/jira/browse/PRO-2738
**1. Change ctx.otherExecName to be set in getContextData() instead of handleGet()**
In getContextData(), ctx.otherExecName will be accessible in the initial page load and if the page is re-rendered due to an error
**2. Improve executors address code**
- Remove generator from handleGet() and handlePost()
- Remove duplicated variable deletion
**3. Add executor address unit tests**
```
[ ] Yes
[x] No
```

PRO-2738 - Executor's name showing as <undefined> on address page (all browsers)

---

app.js
app/config.js
app/healthcheck.js
app/resources/en/translation/common.json
test/config.js
test/end-to-end/paths/cookieBanner.js
test/unit/testHealthcheck.js

https://tools.hmcts.net/jira/browse/PRO-2704
Correct cookie banner so it shows correctly plus other code tidying
- Removed service name from app.js. It now uses the serviceName
in common.json (this is for multi-language).
- Removed version info from app.js as it wasn't used.
- Removed service object from config.js as it's no longer being used.
- Cookies link updated in test/config.js
- Healthcheck and testHealthcheck now refer to serviceName from
common.json (note this is the English version of content, as the service
name written in Welsh in Healthcheck status could confuse).
```
[ ] Yes
[x] No
```

Pro 2704 b cookie banner content missing

---

app/healthcheck.js

**Fix the healthcheck test which was failing after merging the cnp branches into master**
The test broke because the `/health` endpoint wasn't updated after the service name was moved from the config file into the common content file
```
[ ] Yes
[x] No
```

Fix the healthcheck test

---

app/healthcheck.js
app/utils/Healthcheck.js
test/unit/testHealthcheck.js
test/unit/testHealthcheckUtil.js

https://tools.hmcts.net/jira/browse/PRO-3132
Make `/health` status dynamic based on the status of downstream services
```
[ ] Yes
[x] No
```

PRO-3132 - Probate-frontend health check is showing UP even though some of the dependent services are down

---

app/steps/ui/executors/applying/template.html

https://tools.hmcts.net/jira/browse/PRO-1699
Fix missing gap between the `Save and continue` and `Save and close` buttons on the `/other-executors-applying` page
Changed the class of the wrapper around the `Save and continue` button from `.formgroup` to `.form-group`
```
[ ] Yes
[x] No
```

PRO-1699 - Save and Close

---

app/steps/ui/declaration/template.html
app/steps/ui/documents/template.html
app/views/widgets/checkboxes.html

https://tools.hmcts.net/jira/browse/PRO-2789
- For consistency it has been decided to keep the legends (their simple
removal causes our Pa11y tests to fail because the checkbox is contained
in a fieldset which requires a legend)
- The content of the legend has been changed to match the title of the
page
```
[ ] Yes
[x] No
```

PRO-2789 - Change legend on declaration and documents page to match title

---

app/resources/en/translation/common.json
app/views/includes/phase_banner_alpha.html
app/views/includes/phase_banner_beta.html

https://tools.hmcts.net/jira/browse/PRO-2752
Accessibility changes for Public Beta:  Open feedback link in new tab/window
- Added aria-label element to feedback link to assist with accessibility
- Also moved all phase banner and feedback content to common.json
```
[ ] Yes
[x] No
```

PRO-2752: Open feedback link in new tab/window

---

app/steps/ui/payment/breakdown/index.js
test/data/complete-form-undeclared.json
test/service-stubs/payment.js
test/unit/testPaymentBreakdown.js
test/unit/testPaymentStatus.js

https://tools.hmcts.net/jira/browse/PRO-3165
I've cleared the paymentPending and creatingPayment flags (set to null) if there is an authorise failure prior to the createPayment call. This change is required because authorise failures cause the application to get stuck and the user ends up in an endless loop. 
In addition to the flags being cleared, I've also introduced a new unit test. The payment stub was updated to handle undefined paymentId's and send back a HTTP 500 error as per the real service. Because of this I had to update the component test data to include a paymentId which before it had ignored and the stub just returned a successful response.
```
[ ] Yes
[x] No
```

PRO-3165: Fix to handle S2S failures prior to making a payment.

---

app/views/widgets/addresslookup.html
test/component/applicant/testAddress.js
test/util/TestWrapper.js

https://tools.hmcts.net/jira/browse/PRO-1564
- Fix address lookup so the selected address is displayed in the dropdown list if an error occurs
- Add a test method to enable content to be checked on the page if an error occurs
- Add a component test to check that the correct address is displayed in the dropdown list if an error occurs
```
[ ] Yes
[x] No
```

[PREVIEW] PRO-1564 - Select both an address from postcode lookup and manual address - on submit causes lookup select list to reset to "Select address"

---

app/core/steps/AddressStep.js
test/component/applicant/testAddress.js
test/data/find-address.json
test/unit/testAddressStep.js

https://tools.hmcts.net/jira/browse/PRO-3151
- Change AddressStep so it retains all addresses found in the postcode lookup
If the user returns to the address page after selecting an address we want all the available address to be displayed in the address dropdown box rather than just the one the user selected.
- Add a component test to check that the AddressStep retains all addresses found in the postcode lookup
- Update address test data to return 3 addresses rather than just 1
```
[ ] Yes
[x] No
```

[PREVIEW] PRO-3151 - Postcode Lookup - cannot update postcode

---

test/contract/generatepin/testGeneratePin.js

https://tools.hmcts.net/jira/browse/PRO-3459
Update to PRO-3459 to include an extra check for the test response to be an actual number. It would appear sometimes the text response from Notify is returning an error message and this ends up being passed back to the frontend application. With the check in place any messages from Notify which do not match a numerical value will be shown in the console logs.
```
[ ] Yes
[x] No
```

[PREVIEW] Pro 3459 pin not working for international numbers

---

app/components/security.js
app/routes.js
app/steps/ui/payment/breakdown/index.js
test/unit/testPaymentBreakdown.js

https://tools.hmcts.net/jira/browse/PRO-3858
We need to do this because the formdata gets set without the applicantEmail during the screener questions and the applicantEmail needs to be set after returning from IDAM
```
[ ] Yes
[x] No
```

[PREVIEW] PRO-3858 -Check formdata contains applicantEmail and set it if not

---

app.js
app/assets/javascripts/document-upload.js
app/config.js
app/resources/en/translation/common.json
app/views/includes/scripts.html

https://tools.hmcts.net/jira/browse/PRO-3755
**Add validation for the number of files.**
- Only 10 files may be uploaded and this should work when using the files selector and dragging/dropping.
- If you have multiple error messages displaying on the file list and you remove all the files for an error message then the error summary is also updated to remove reference to that error message.
- If you drag 12 files into the Dropzone and get 2 error messages then remove 2 of the uploaded files, the error messages remain even though you've now only uploaded 8 files...discussed and agreed with Femi and Davy.
```
[ ] Yes
[x] No
```

[PREVIEW] PRO-3755 - Upload death certificate - Max Files

---

app/config.js
app/steps/ui/payment/breakdown/index.js
app/steps/ui/payment/status/index.js
test/component/payment/testPaymentBreakdown.js
test/unit/testPaymentBreakdown.js
test/unit/testPaymentStatus.js

- Stop a payment being created when status of the payment is already "Success" or "Initiated".
- Stop case status being updated to failed, when payment response status is "Initiated".
The above stops duplicates and handles payments with "Initiated" status better.
```
[ ] Yes
[X] No
```

PRO-3915: Stop duplicate payments

---

app/routes.js
app/steps/ui/payment/status/index.js
test/component/payment/testPaymentStatus.js
test/component/testRedirectToDocuments.js
test/data/complete-form.json
test/unit/testPaymentStatus.js
test/unit/testTasklist.js

https://tools.hmcts.net/jira/browse/PRO-3790
Update to the payment-status page to detect the state of the CCD payment update and to show an error if caseState does not match 'CaseCreated'. The logic for this is as follows.
1. Check we have a valid payment response if so then...
2. Check we have a valid ccd update response if so then confirm response is 'CaseCreated'.
3. Update case status in formdata.
4. If either payment response or ccd update response is not valid then stay on payment-status and show error, otherwise move to documents page.
I've also updated the routes.js to properly detect the conditions for being on the documents page which was missing the state of the ccd update matching 'CaseCreated'.
```
[ ] Yes
[x] …
```

[PREVIEW] PRO-3790: Fix to allow case to be updated after submit service is down.

---

app/assets/javascripts/document-upload.js
app/assets/sass/patterns/_document-upload.scss
app/documentUpload.js
app/resources/en/translation/common.json
app/routes.js
app/steps/ui/documentupload/index.js
app/steps/ui/documentupload/template.html
app/utils/DocumentUpload.js
app/views/includes/document-upload.html
app/views/includes/two_thirds_form.html
test/unit/testDocumentUploadUtil.js

https://tools.hmcts.net/jira/browse/PRO-3749
Add javascript fallback for when javascript is disabled.
Files can be added one at a time by selecting a file and clicking 'Upload document'. As a file is uploaded it is displayed in the list below the file upload form.
The files are saved into the session so the file list is displayed when refreshing the page.
Validation is done in the following stories.
```
[ ] Yes
[x] No
```

[PREVIEW] PRO-3749 - Upload death certificate - Non-JS

---

app/resources/en/translation/summary.json
app/steps/ui/summary/includes/documentupload.njk
app/steps/ui/summary/template.html
app/views/widgets/checkanswer.html
test/component/summary/testDocumentUploadSection.js
test/component/summary/testSummary.js

https://tools.hmcts.net/jira/browse/PRO-4273
Display the uploaded documents section on the summary page with a default message when no documents have been uploaded so it gives the user a chance to return to the document upload page to add upload documents.
```
[ ] Yes
[x] No
```

PRO-4273 - Doc Upload: Documents section should still be present on CYA even if no Doc uploaded

---

app/steps/ui/payment/status/index.js
test/unit/testPaymentStatus.js

https://tools.hmcts.net/jira/browse/PRO-5376
After cancelling a payment, if the user logs out and logs in again and completes a successful payment the payment validation on /payment-status still uses the old failed reference which doesn't return caseState value and results in the formdata entry being wiped.
This simple change just checks the caseState value is populated first before writing to the formdata. Included an extra check in the unit tests.
```
[ ] Yes
[x] No
```

PRO-5376: Fix to not clear case state if undefined.

---

app/views/errors/403.html
app/views/errors/404.html
app/views/errors/500.html

https://tools.hmcts.net/jira/browse/PRO-6270
Replace current url on survey links appearing on error pages
```
[ ] Yes
[X] No
```

PRO-6270: Replace current url on survey links appearing on error pages

---

test/unit/payment/testPaymentStatus.js

https://tools.hmcts.net/jira/browse/PRO-6869
Add 2 unit tests for Payment Status to increase code coverage in Sonar Scan
```
[ ] Yes
[X] No
```

PRO-6869: Add 2 unit tests for Payment Status

---

app/utils/FeatureToggle.js
test/unit/utils/testFeatureToggle.js

https://tools.hmcts.net/jira/browse/PRO-7305
Only check for LaunchDarkly ready event once
```
[ ] Yes
[X] No
```

PRO-7305: Call ready check once

---

Jenkinsfile_nightly
config/testing-http-dk.yaml
test/end-to-end/codecept.conf.js
test/end-to-end/helpers/IDAMHelper.js
test/end-to-end/helpers/JSWait.js
test/end-to-end/helpers/LaunchDarkly.js
test/end-to-end/helpers/TestConfigurator.js
test/end-to-end/paths/generic/cookieBanner.test.js
test/end-to-end/paths/generic/survey.test.js
test/end-to-end/paths/intestacy/intestacy.en.test.js
test/end-to-end/paths/intestacy/intestacy.spouse.en.test.js
test/end-to-end/paths/probate/gopSingleExecutor.en.test.js
test/end-to-end/paths/probate/multipleExecutors.js
test/end-to-end/saucelabs.conf.js

Sub-task: https://tools.hmcts.net/jira/browse/DTSPB-1014
Parent Task: https://tools.hmcts.net/jira/browse/DTSPB-999
This change includes the following to get the crossbrowser tests running successfully on Chrome:
- refactor LaunchDarkly initialisation in TestConfigurator.js, so that LaunchDarkly is only initialised and closed by tests that require it.
- refactor IDAM test user creation so that it can take advantage of Codecept's `.retry()` functionality
- delete IDAM test user during test teardown to help protect IDAM (apparently the source of some IDAM errors is due to the volume of stale test accounts)
- reduce number of retries so as not to waste time when a persistent failure is hit (this can cause Jenkins to timeout and so not test all browsers)
- ~~run only the working e2e tests …

DTSPB-999: Get crossbrowser tests running on Chrome

---

package.json
yarn.lock

https://tools.hmcts.net/jira/browse/DTSPB-2284
- probate FE nightly builds are failing because of vulnerability with url-parse module.
```
[ ] Yes
[x] No
```

DTSPB-2284 - Upgrade launchdarkly-node-server-sdk 5.13.3 -> 6.2.0

---

app.js
test/java/build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2280
- There is a critical issue for probate-frontend and probate-frontend-caveats where the explanation is given as:
The SSLv2, SSLv23, and SSLv3 protocols contain several flaws that make them insecure, so they should not be used to transmit sensitive data.
- This issue needs to be fixed so that Fortify scan step passes in the build.
```
[ ] Yes
[x] No
```

DTSPB-2280 - Add specified "secureProtocol" to fix Fortify scan issue

---

test/end-to-end/pages/executors/names.js

Updated e2e tests to make the executor names it uses use letters instead of numbers as numbers aren't allowed in the field i.e. exec2 to execB
```
[ ] Yes
[x] No
```

fix for execNames field e2e from regex update
